<?php

return [
    /* Groups of the font repertoire, in the order the editor lists them. */
    'font_categories' => [
        'serif' => ['label' => 'Serif clásicas', 'text' => 'De libro: serias, cálidas y muy legibles en párrafos largos.'],
        'titular' => ['label' => 'Serif de titular', 'text' => 'Elegantes y con contraste, para títulos grandes y portadas.'],
        'sans' => ['label' => 'Sin serifa modernas', 'text' => 'Limpias y geométricas: la voz actual de la web.'],
        'humanist' => ['label' => 'Sin serifa humanistas', 'text' => 'Cercanas y amables, ideales para textos y menús.'],
        'round' => ['label' => 'Redondeadas', 'text' => 'Suaves y alegres, para niños, jóvenes y acentos.'],
        'script' => ['label' => 'Caligráficas', 'text' => 'Cursivas formales para frases cortas, nunca para párrafos.'],
        'hand' => ['label' => 'Manuscritas', 'text' => 'Escritas a mano, informales: notas, firmas y frases.'],
        'display' => ['label' => 'Display e impacto', 'text' => 'Llamativas y de cartel, para una o dos palabras grandes.'],
        'slab' => ['label' => 'Slab · egipcias', 'text' => 'Serifa gruesa y firme, robusta en títulos y botones.'],
        'mono' => ['label' => 'Monoespaciadas', 'text' => 'De máquina de escribir: cifras, horarios y detalles técnicos.'],
    ],

    /*
     * Families offered in the editor, by category. "local" ones ship with the site (resources/css/fonts.css);
     * the rest load from fonts.bunny.net only when a page uses them. "kind" picks the fallback while a family loads.
     */
    'fonts' => [
        ['name' => 'Fraunces', 'slug' => 'fraunces', 'kind' => 'serif', 'category' => 'serif', 'local' => true],
        ['name' => 'Lora', 'slug' => 'lora', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'EB Garamond', 'slug' => 'eb-garamond', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Cormorant Garamond', 'slug' => 'cormorant-garamond', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Libre Baskerville', 'slug' => 'libre-baskerville', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Merriweather', 'slug' => 'merriweather', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Crimson Pro', 'slug' => 'crimson-pro', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Spectral', 'slug' => 'spectral', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Source Serif 4', 'slug' => 'source-serif-4', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Noto Serif', 'slug' => 'noto-serif', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'PT Serif', 'slug' => 'pt-serif', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Cardo', 'slug' => 'cardo', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Literata', 'slug' => 'literata', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Newsreader', 'slug' => 'newsreader', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Alegreya', 'slug' => 'alegreya', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Libre Caslon Text', 'slug' => 'libre-caslon-text', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Old Standard TT', 'slug' => 'old-standard-tt', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Vollkorn', 'slug' => 'vollkorn', 'kind' => 'serif', 'category' => 'serif'],
        ['name' => 'Young Serif', 'slug' => 'young-serif', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'DM Serif Display', 'slug' => 'dm-serif-display', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Playfair Display', 'slug' => 'playfair-display', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Abril Fatface', 'slug' => 'abril-fatface', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Bodoni Moda', 'slug' => 'bodoni-moda', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Prata', 'slug' => 'prata', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Cinzel', 'slug' => 'cinzel', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Cormorant', 'slug' => 'cormorant', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Gloock', 'slug' => 'gloock', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Rozha One', 'slug' => 'rozha-one', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Yeseva One', 'slug' => 'yeseva-one', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Marcellus', 'slug' => 'marcellus', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Italiana', 'slug' => 'italiana', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Libre Bodoni', 'slug' => 'libre-bodoni', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Noto Serif Display', 'slug' => 'noto-serif-display', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Instrument Serif', 'slug' => 'instrument-serif', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Cinzel Decorative', 'slug' => 'cinzel-decorative', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Forum', 'slug' => 'forum', 'kind' => 'serif', 'category' => 'titular'],
        ['name' => 'Inter', 'slug' => 'inter', 'kind' => 'sans', 'category' => 'sans', 'local' => true],
        ['name' => 'Inter Tight', 'slug' => 'inter-tight', 'kind' => 'sans', 'category' => 'sans', 'local' => true],
        ['name' => 'DM Sans', 'slug' => 'dm-sans', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Manrope', 'slug' => 'manrope', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Plus Jakarta Sans', 'slug' => 'plus-jakarta-sans', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Montserrat', 'slug' => 'montserrat', 'kind' => 'sans', 'category' => 'sans', 'local' => true],
        ['name' => 'Poppins', 'slug' => 'poppins', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Outfit', 'slug' => 'outfit', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Raleway', 'slug' => 'raleway', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Work Sans', 'slug' => 'work-sans', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Figtree', 'slug' => 'figtree', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Sora', 'slug' => 'sora', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Urbanist', 'slug' => 'urbanist', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Lexend', 'slug' => 'lexend', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Red Hat Display', 'slug' => 'red-hat-display', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Albert Sans', 'slug' => 'albert-sans', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Be Vietnam Pro', 'slug' => 'be-vietnam-pro', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Onest', 'slug' => 'onest', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Space Grotesk', 'slug' => 'space-grotesk', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Archivo', 'slug' => 'archivo', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Rubik', 'slug' => 'rubik', 'kind' => 'sans', 'category' => 'sans'],
        ['name' => 'Open Sans', 'slug' => 'open-sans', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Lato', 'slug' => 'lato', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Source Sans 3', 'slug' => 'source-sans-3', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Noto Sans', 'slug' => 'noto-sans', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Fira Sans', 'slug' => 'fira-sans', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'PT Sans', 'slug' => 'pt-sans', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Mulish', 'slug' => 'mulish', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Cabin', 'slug' => 'cabin', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Hind', 'slug' => 'hind', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Karla', 'slug' => 'karla', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Libre Franklin', 'slug' => 'libre-franklin', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Ubuntu', 'slug' => 'ubuntu', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Nunito Sans', 'slug' => 'nunito-sans', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Josefin Sans', 'slug' => 'josefin-sans', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Asap', 'slug' => 'asap', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Alegreya Sans', 'slug' => 'alegreya-sans', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Encode Sans', 'slug' => 'encode-sans', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Overpass', 'slug' => 'overpass', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Tenor Sans', 'slug' => 'tenor-sans', 'kind' => 'sans', 'category' => 'humanist'],
        ['name' => 'Fredoka', 'slug' => 'fredoka', 'kind' => 'round', 'category' => 'round', 'local' => true],
        ['name' => 'Nunito', 'slug' => 'nunito', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Quicksand', 'slug' => 'quicksand', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Varela Round', 'slug' => 'varela-round', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Baloo 2', 'slug' => 'baloo-2', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Comfortaa', 'slug' => 'comfortaa', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'M PLUS Rounded 1c', 'slug' => 'm-plus-rounded-1c', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Dosis', 'slug' => 'dosis', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Sniglet', 'slug' => 'sniglet', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Signika', 'slug' => 'signika', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Grandstander', 'slug' => 'grandstander', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Andika', 'slug' => 'andika', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Kosugi Maru', 'slug' => 'kosugi-maru', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Zen Maru Gothic', 'slug' => 'zen-maru-gothic', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Mitr', 'slug' => 'mitr', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Gluten', 'slug' => 'gluten', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Kodchasan', 'slug' => 'kodchasan', 'kind' => 'round', 'category' => 'round'],
        ['name' => 'Great Vibes', 'slug' => 'great-vibes', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Parisienne', 'slug' => 'parisienne', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Allura', 'slug' => 'allura', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Alex Brush', 'slug' => 'alex-brush', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Pinyon Script', 'slug' => 'pinyon-script', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Tangerine', 'slug' => 'tangerine', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Italianno', 'slug' => 'italianno', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Dancing Script', 'slug' => 'dancing-script', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Sacramento', 'slug' => 'sacramento', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Rouge Script', 'slug' => 'rouge-script', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Mrs Saint Delafield', 'slug' => 'mrs-saint-delafield', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Petit Formal Script', 'slug' => 'petit-formal-script', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Herr Von Muellerhoff', 'slug' => 'herr-von-muellerhoff', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Imperial Script', 'slug' => 'imperial-script', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Corinthia', 'slug' => 'corinthia', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'WindSong', 'slug' => 'windsong', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Birthstone', 'slug' => 'birthstone', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Pacifico', 'slug' => 'pacifico', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Satisfy', 'slug' => 'satisfy', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Cookie', 'slug' => 'cookie', 'kind' => 'script', 'category' => 'script'],
        ['name' => 'Caveat', 'slug' => 'caveat', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Kalam', 'slug' => 'kalam', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Patrick Hand', 'slug' => 'patrick-hand', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Indie Flower', 'slug' => 'indie-flower', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Shadows Into Light', 'slug' => 'shadows-into-light', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Amatic SC', 'slug' => 'amatic-sc', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Gloria Hallelujah', 'slug' => 'gloria-hallelujah', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Architects Daughter', 'slug' => 'architects-daughter', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Handlee', 'slug' => 'handlee', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Gochi Hand', 'slug' => 'gochi-hand', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Covered By Your Grace', 'slug' => 'covered-by-your-grace', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Permanent Marker', 'slug' => 'permanent-marker', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Reenie Beanie', 'slug' => 'reenie-beanie', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Rock Salt', 'slug' => 'rock-salt', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Just Another Hand', 'slug' => 'just-another-hand', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Coming Soon', 'slug' => 'coming-soon', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Itim', 'slug' => 'itim', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Mali', 'slug' => 'mali', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Delius', 'slug' => 'delius', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Schoolbell', 'slug' => 'schoolbell', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Neucha', 'slug' => 'neucha', 'kind' => 'script', 'category' => 'hand'],
        ['name' => 'Bebas Neue', 'slug' => 'bebas-neue', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Anton', 'slug' => 'anton', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Oswald', 'slug' => 'oswald', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Archivo Black', 'slug' => 'archivo-black', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Righteous', 'slug' => 'righteous', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Bungee', 'slug' => 'bungee', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Lobster', 'slug' => 'lobster', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Alfa Slab One', 'slug' => 'alfa-slab-one', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Bowlby One SC', 'slug' => 'bowlby-one-sc', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Passion One', 'slug' => 'passion-one', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Fjalla One', 'slug' => 'fjalla-one', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Staatliches', 'slug' => 'staatliches', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Teko', 'slug' => 'teko', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Russo One', 'slug' => 'russo-one', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Monoton', 'slug' => 'monoton', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Titan One', 'slug' => 'titan-one', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Luckiest Guy', 'slug' => 'luckiest-guy', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Bangers', 'slug' => 'bangers', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Ultra', 'slug' => 'ultra', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Rye', 'slug' => 'rye', 'kind' => 'sans', 'category' => 'display'],
        ['name' => 'Roboto Slab', 'slug' => 'roboto-slab', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Zilla Slab', 'slug' => 'zilla-slab', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Arvo', 'slug' => 'arvo', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Bitter', 'slug' => 'bitter', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Josefin Slab', 'slug' => 'josefin-slab', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Aleo', 'slug' => 'aleo', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Crete Round', 'slug' => 'crete-round', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Bree Serif', 'slug' => 'bree-serif', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Noticia Text', 'slug' => 'noticia-text', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Rokkitt', 'slug' => 'rokkitt', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Podkova', 'slug' => 'podkova', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Slabo 27px', 'slug' => 'slabo-27px', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Kameron', 'slug' => 'kameron', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Patua One', 'slug' => 'patua-one', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Sanchez', 'slug' => 'sanchez', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Glegoo', 'slug' => 'glegoo', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'Enriqueta', 'slug' => 'enriqueta', 'kind' => 'serif', 'category' => 'slab'],
        ['name' => 'JetBrains Mono', 'slug' => 'jetbrains-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'IBM Plex Mono', 'slug' => 'ibm-plex-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Space Mono', 'slug' => 'space-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Fira Code', 'slug' => 'fira-code', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Source Code Pro', 'slug' => 'source-code-pro', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Roboto Mono', 'slug' => 'roboto-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Inconsolata', 'slug' => 'inconsolata', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Courier Prime', 'slug' => 'courier-prime', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'DM Mono', 'slug' => 'dm-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Ubuntu Mono', 'slug' => 'ubuntu-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Overpass Mono', 'slug' => 'overpass-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Red Hat Mono', 'slug' => 'red-hat-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Azeret Mono', 'slug' => 'azeret-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Martian Mono', 'slug' => 'martian-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Anonymous Pro', 'slug' => 'anonymous-pro', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Cousine', 'slug' => 'cousine', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Xanh Mono', 'slug' => 'xanh-mono', 'kind' => 'mono', 'category' => 'mono'],
        ['name' => 'Spline Sans Mono', 'slug' => 'spline-sans-mono', 'kind' => 'mono', 'category' => 'mono'],
    ],

    /* Every public page, keyed by its Inertia component. "slug" pages preview their first published item. */
    'pages' => [
        'Home' => ['label' => 'Inicio', 'path' => '/'],
        'About' => ['label' => 'Conócenos', 'path' => '/conocenos'],
        'Ministries' => ['label' => 'Ministerios', 'path' => '/ministerios'],
        'Ministry' => ['label' => 'Ministerio (detalle)', 'path' => '/ministerios/{slug}', 'slug' => 'ministry'],
        'Visit' => ['label' => 'Planifica tu visita', 'path' => '/visita'],
        'Baptisms' => ['label' => 'Bautismos', 'path' => '/bautismos'],
        'Sermons' => ['label' => 'Prédicas', 'path' => '/predicas'],
        'Teachings' => ['label' => 'Recursos', 'path' => '/recursos'],
        'Events' => ['label' => 'Eventos', 'path' => '/eventos'],
        'Galleries' => ['label' => 'Galería', 'path' => '/galeria'],
        'Gallery' => ['label' => 'Álbum de galería', 'path' => '/galeria/{slug}', 'slug' => 'gallery'],
        'Devotionals' => ['label' => 'Devocionales', 'path' => '/devocionales'],
        'Devotional' => ['label' => 'Devocional (lectura)', 'path' => '/devocionales/{slug}', 'slug' => 'devotional'],
        'Serve' => ['label' => 'Involúcrate', 'path' => '/involucrate'],
        'ServeArea' => ['label' => 'Área de servicio', 'path' => '/involucrate/{slug}', 'slug' => 'serve'],
        'ServerRoute' => ['label' => 'Ruta del servidor', 'path' => '/ruta-del-servidor'],
        'Radio' => ['label' => 'Radio', 'path' => '/radio'],
        'Give' => ['label' => 'Generosidad', 'path' => '/dar'],
        'Contact' => ['label' => 'Contacto', 'path' => '/contacto'],
        'Acceso' => ['label' => 'Acceso al sistema', 'path' => '/acceso'],
        'Estudios/Acceso' => ['label' => 'Acceso de estudiantes', 'path' => '/estudios/acceso'],
        'AccesoAdmin' => ['label' => 'Acceso del panel', 'path' => '/acceso', 'host' => 'admin'],
    ],

    /* Page keys saved before the editor knew every page. */
    'legacy_pages' => [
        'home' => ['Home'],
        'about' => ['About'],
        'ministries' => ['Ministries', 'Ministry'],
        'visit' => ['Visit'],
        'baptisms' => ['Baptisms'],
        'sermons' => ['Sermons'],
        'give' => ['Give'],
        'contact' => ['Contact'],
        'acceso' => ['Acceso'],
    ],

    /* Drawings and animations the editor can recolor, slow down, freeze or hide. An empty color follows the palette accent. */
    'art' => [
        'acceso' => [
            'label' => 'Escena del acceso',
            'text' => 'El ánfora de madera que muestra versículos en su placa y recibe por la ranura los sobres de célula con el sello de Zoe.',
            'page' => 'Acceso',
            'can_hide' => true,
            'colors' => [
                'sky' => ['label' => 'Fondo', 'value' => '#f0e4d4'],
                'desk' => ['label' => 'Piso', 'value' => '#c9ae96'],
                'jar' => ['label' => 'Madera del ánfora', 'value' => '#9a6238'],
                'accent' => ['label' => 'Sello de los sobres', 'value' => '#c45c26'],
                'gold' => ['label' => 'Dorado', 'value' => '#e0b062'],
            ],
        ],
        'prayer' => [
            'label' => 'Luz de oración',
            'text' => 'Los halos de «Cómo oramos por ti» y el brillo al enviar una petición.',
            'page' => 'Contact',
            'can_hide' => false,
            'colors' => [
                'accent' => ['label' => 'Halos', 'value' => ''],
                'glow' => ['label' => 'Brillo', 'value' => '#f0d090'],
            ],
        ],
        'study' => [
            'label' => 'Vista del aula',
            'text' => 'La ilustración de la plataforma de estudios.',
            'page' => 'ServerRoute',
            'can_hide' => true,
            'colors' => [
                'background' => ['label' => 'Fondo', 'value' => '#ebe4da'],
                'accent' => ['label' => 'Acento', 'value' => ''],
            ],
        ],
        'radio' => [
            'label' => 'Ecualizador de la radio',
            'text' => 'Las barras que se mueven con la música.',
            'page' => 'Radio',
            'can_hide' => false,
            'colors' => [
                'bars' => ['label' => 'Barras', 'value' => '#ffffff'],
            ],
        ],
        'rail' => [
            'label' => 'Carrusel de servicio',
            'text' => 'El zoom suave de la foto activa en «Involúcrate».',
            'page' => 'Home',
            'can_hide' => false,
            'colors' => [],
        ],
        'write' => [
            'label' => 'Frase que se escribe sola',
            'text' => 'La cita que aparece letra por letra.',
            'page' => 'About',
            'can_hide' => false,
            'colors' => [],
        ],
        'cue' => [
            'label' => 'Flecha «desliza»',
            'text' => 'La flecha que invita a bajar en la portada.',
            'page' => 'About',
            'can_hide' => true,
            'colors' => [],
        ],
        'reveal' => [
            'label' => 'Aparición al desplazar',
            'text' => 'Títulos, textos y fotos que aparecen al bajar por cualquier página.',
            'page' => null,
            'can_hide' => false,
            'colors' => [],
        ],
    ],

    'defaults' => [
        'palette' => [
            'paper' => '#fdfcfa',
            'card' => '#ffffff',
            'ink' => '#1a1a1a',
            'muted' => '#5c5853',
            'line' => '#e7e1d8',
            'accent' => '#c14a09',
            'stone' => '#ebe4da',
            'clay' => '#ead8c9',
        ],
        'fonts' => [
            'heading' => 'Montserrat',
            'text' => 'Inter',
            'accent' => 'Fredoka',
        ],
        'sizes' => [
            'title' => 1,
            'subtitle' => 1,
            'text' => 1,
        ],
        'shape' => 'round',
    ],
];
