<?php

return [
    /*
     * Administrators and the superadmin sign in only on these hosts; servers
     * (célula, hijo, red) sign in on the church site.
     */
    'admin_hosts' => array_values(array_filter(array_map(
        fn ($host) => strtolower(trim($host)),
        explode(',', (string) env('ZOE_ADMIN_HOSTS', 'admi-iglesiazoe.miacademiapreu.com,admin.localhost')),
    ))),
    'site_url' => rtrim((string) env('ZOE_SITE_URL', 'https://iglesiacristianazoe.miacademiapreu.com'), '/'),
    'admin_url' => rtrim((string) env('ZOE_ADMIN_URL', 'https://admi-iglesiazoe.miacademiapreu.com'), '/'),

    'settings' => [
        'heroTitle' => 'Vida en abundancia para ti y los tuyos.',
        'heroSubtitle' => 'No importa por dónde hayas pasado ni cuál sea tu historia. Este es un espacio seguro para conectar con Dios, con otros y empezar de nuevo. Bienvenido a casa.',
        'essenceTitle' => 'El origen de nuestro nombre',
        'essenceText' => "Zoe (ζωή) es la palabra griega para «vida»: la vida abundante que Jesús prometió en Juan 10:10, «Yo he venido para que tengan vida, y para que la tengan en abundancia».\n\nHace más de 30 años esa promesa nos dio nombre. Creemos que si lo tienes a Él, lo tienes todo: plenitud en lo personal, familiar, económico y espiritual. Más que una congregación, somos una familia.",
        'cellsTitle' => 'Nadie camina solo en Zoe',
        'cellsText' => "Creemos que la fe no se vive en solitario ni se limita a cuatro paredes una vez por semana. Nuestro verdadero latido sucede en las casas.\n\nCada semana nos reunimos en grupos pequeños para compartir la palabra, orar los unos por los otros, cenar y sostenernos en comunidad. Aquí nadie es un número; aquí encuentras un verdadero hogar.",
        'cellsCta' => 'Encuentra un grupo en tu zona',
        'generationsTitle' => 'Un lugar para cada generación',
        'resourcesTitle' => 'Palabra para tu semana',
        'resourcesText' => 'Mira los mensajes más recientes y vuelve a ellos cuando los necesites.',
        'visitInviteTitle' => '¿Nos acompañas este domingo?',
        'visitInviteText' => 'Queremos conocerte y recibirte como en casa. Ven a celebrar, cantar y vivir un tiempo juntos.',
        'city' => 'Chiclayo, Lambayeque',
        'address' => 'Simón Bolívar 750, Chiclayo',
        'sunday' => 'Domingos 10:30 a.m.',
        'wednesday' => 'Miércoles 8:00 p.m.',
        'pastorsLabel' => 'Pastores Alberto y Kelly Dávila',
        'aboutQuote' => 'Somos creyentes de Jesús y embajadores de él. Ven y forma parte de un reino que vive en abundancia.',
        'aboutText' => 'Somos una comunidad en Chiclayo, departamento de Lambayeque en Perú, y nos une la fe en Dios Padre, Dios Hijo y el Espíritu Santo. Reconocemos haber recibido provisión de Dios siendo pastoreados con amor.',
        'vision' => 'Ver vidas transformadas por Jesús en cada casa, cada generación y cada rincón de nuestra ciudad. Una iglesia local donde el amor de Dios se vuelve visible.',
        'history' => 'Iglesia Cristiana Zoe nació en Chiclayo como una familia de fe. Crecemos en células —nuestros grupos celulares— y en los servicios de la congregación, formando discípulos que llevan el amor de Cristo a su casa, su campus y su trabajo.',
        'values' => [
            ['title' => 'Amor', 'text' => 'El amor de Dios es la atmósfera de nuestra casa. Recibimos a cada persona con dignidad.'],
            ['title' => 'Palabra', 'text' => 'La Escritura guía nuestra fe, nuestros hogares y la manera en que servimos.'],
            ['title' => 'Comunidad', 'text' => 'Nadie crece solo. Las células y los ministerios son el lugar donde la fe se hace familia.'],
            ['title' => 'Generosidad', 'text' => 'Dar es adoración. Sostenemos la obra y alcanzamos a quienes más lo necesitan.'],
        ],
        'facebook' => 'https://www.facebook.com/iglesiacristianazoe',
        'youtube' => 'https://www.youtube.com/@iglesiacristianazoe6279',
        'instagram' => 'https://www.instagram.com/iglesiacristianazoe/',
        'tiktok' => 'https://www.tiktok.com/@iglesiacristianazoe',
        'messengerUrl' => 'https://m.me/iglesiacristianazoe',
        'mapUrl' => 'https://maps.app.goo.gl/AR25odttLqLoUrS18',
        'serviceDayMain' => '0',
        'serviceDayWeek' => '3',
        'prayerTopics' => ['Salud', 'Familia', 'Trabajo y finanzas', 'Vida espiritual', 'Estudios', 'Gratitud', 'Otro'],
        'copy' => [],
        'bankSoles' => '3052651989073',
        'bankSolesCci' => '00230500265198907310',
        'bankDollars' => '',
        'bankDollarsCci' => '',
        'bankHolder' => 'Iglesia Cristiana de Fe Zoe',
        'yape' => '',
        'yapeHolder' => 'Iglesia Cristiana de Fe Zoe',
        'yapeQr' => '/images/yape-qr.png',
        'cardUrl' => '',
        'phone' => '(074) 252525',
        'whatsapp' => '',
        'email' => 'iglesiacristianazoe@gmail.com',
        'baptismCta' => '¡Quiero bautizarme!',
        'footerTagline' => 'Una familia en Chiclayo, donde el amor de Dios se hace casa.',
        'aboutTitle' => 'Una iglesia local, una sola familia.',
        'aboutValuesTitle' => 'Lo que nos sostiene.',
        'aboutValuesText' => 'Estos valores no son un lema. Son la manera en que pastoreamos, nos reunimos y servimos a Chiclayo.',
        'ministriesTitle' => 'Un lugar para cada etapa de la vida.',
        'ministriesText' => 'Desde los niños hasta los matrimonios, hay una comunidad donde puedes pertenecer, crecer y servir.',
        'baptismTitle' => 'Tu nuevo comienzo',
        'baptismLead' => 'Da el siguiente paso en tu fe.',
        'baptismBody' => 'Creemos que el bautismo en agua es una declaración pública de tu fe en Jesucristo. Es el símbolo de dejar atrás la vieja manera de vivir y nacer a una nueva vida en Él. Si has tomado la decisión de seguir a Jesús, este es el siguiente paso más importante que puedes dar.',
        'baptismDateLabel' => 'Próxima fecha',
        'baptismRequirementLabel' => 'Requisito',
        'baptismRequirement' => 'Asistir a la charla informativa previa.',
        'baptismDateFallback' => 'Fecha por confirmar',
        'visitTitle' => 'Planifica tu visita',
        'visitText' => 'Nos encantaría recibirte. Llena este formulario y un equipo de bienvenida estará atento para acompañarte.',
        'contactTitle' => 'Estamos para acompañarte.',
        'prayerTitle' => 'Petición de oración',
        'giveTitle' => 'Generosidad que transforma vidas',
        'giveLead' => 'Sé parte de lo que Dios está haciendo en nuestra iglesia y comunidad.',
        'giveBody' => 'Dar es adoración. Tu generosidad sostiene la obra y alcanza a quienes más lo necesitan.',
        'giveYapeText' => 'Escanea el código o envía tu aporte al número de la iglesia.',
        'giveCardText' => 'Aporta en línea con la pasarela de pagos de la iglesia.',
        'giveAbroadText' => 'Si vives fuera del Perú, envía tu ofrenda por transferencia internacional a nuestra cuenta del BCP con el código SWIFT. Luego escríbenos para confirmar tu aporte.',
        'bankSwift' => 'BCPLPEPL',
        'baptismVideo' => '',
        'baptismVideoTitle' => '¿Qué es el bautismo?',
        'baptismVideoText' => 'Nuestros pastores te explican en pocos minutos qué significa bautizarte y cómo prepararte.',
        'eventsTitle' => 'Lo que se viene en la casa',
        'eventsText' => 'Celebraciones, retiros y encuentros para vivir en familia.',
        'teachingsTitle' => 'Palabra para llevar a casa',
        'teachingsText' => 'La enseñanza de cada prédica y el material de los GC, listos para repasar y compartir.',
        'serveTitle' => 'Hay un lugar para ti',
        'serveText' => 'Servir es un privilegio y una expresión de nuestro amor por Dios y por las personas. Descubre el área donde tus dones bendicen a otros y únete a un equipo.',
        'serveRailTitle' => 'Somos una iglesia que *está en movimiento*',
        'serveRailText' => 'Contribuimos con nuestro país. Llevamos esperanza, fe y el mensaje de Jesús a cada persona.',
        'routeTitle' => 'La Ruta del Servidor',
        'routeText' => 'El camino de estudios de Zoe: cinco niveles para crecer paso a paso, desde tu nueva vida en Jesús hasta servir y acompañar a otros en un grupo celular.',
        'routeLevels' => [
            ['title' => 'Encuentro', 'text' => 'Conoces a Jesús, sanas tu historia y das tus primeros pasos en la casa.'],
            ['title' => 'Discipulado', 'text' => 'Construyes bases firmes en la Palabra, la oración y la vida en comunidad.'],
            ['title' => 'Liderazgo', 'text' => 'Aprendes a cuidar y acompañar a otros dentro de un grupo celular.'],
            ['title' => 'Servidor', 'text' => 'Recibes tu grupo y comienzas a servir como servidor de célula.'],
        ],
        'sermonsTitle' => 'En vivo y mensajes',
        'sermonsEmpty' => 'La transmisión se publica aquí cada servicio.',
    ],
    'weekly_notice' => [
        'enabled' => true,
        'kicker' => 'Indicaciones de la semana',
        'title' => 'Antes de reunirte con tu grupo',
        'period' => '',
        'intro' => 'Querido servidor, gracias por cuidar de tu grupo celular. Estos son los puntos que debes tener en cuenta esta semana.',
        'points' => [
            ['title' => 'Envía tu informe a tiempo', 'text' => 'Registra el informe de tu grupo CEREAL a más tardar el domingo a las 11:59 p. m., con asistencia, ofrenda y fotos de la reunión.'],
            ['title' => 'Prepara el tema con anticipación', 'text' => 'Descarga el tema de la semana desde «Temas de célula» y dedícale un tiempo de oración antes de compartirlo.'],
            ['title' => 'Ofrendas y diezmos', 'text' => 'Anota los montos exactos recibidos y entrégalos a tu servidor de red el domingo durante el servicio.'],
            ['title' => 'Fotos de la reunión', 'text' => 'Sube al menos una foto clara donde se vea al grupo reunido.'],
            ['title' => 'Acompaña a los nuevos', 'text' => 'Si llegó alguien por primera vez, regístralo como integrante y escríbele durante la semana para darle la bienvenida.'],
        ],
        'closing' => 'Equipo pastoral · Iglesia Cristiana Zoe',
    ],
    /** Levels of La Ruta del Servidor created on first install; from then on they are managed in the admin (Estudios). */
    'study_levels' => [
        ['slug' => 'nueva-vida', 'name' => 'Nueva Vida', 'summary' => 'Los fundamentos de tu nueva vida en Cristo: la salvación, el perdón, la oración y la Palabra de Dios.'],
        ['slug' => 'enraizados', 'name' => 'Enraizados', 'summary' => 'Echa raíces firmes en la fe: tu identidad en Cristo, la obra del Espíritu Santo y la vida en comunidad.'],
        ['slug' => 'grandeza-del-servicio', 'name' => 'Grandeza del Servicio', 'summary' => 'Descubre tus dones y aprende a servir a otros con el corazón y la excelencia de Jesús.'],
        ['slug' => 'discipulado', 'name' => 'Discipulado', 'summary' => 'Aprende a acompañar a otros en su crecimiento, como Jesús lo hizo con sus discípulos.'],
        ['slug' => 'vision-celular', 'name' => 'Visión Celular', 'summary' => 'La visión de la iglesia en las casas: cómo abrir, cuidar y multiplicar un grupo celular.'],
    ],
    /** Starter encouragement verses for the students' classroom. */
    'study_verses' => [
        ['Filipenses 1:6', 'El que comenzó en ustedes la buena obra la irá perfeccionando hasta el día de Cristo Jesús.'],
        ['Josué 1:9', 'Sé fuerte y valiente. No temas ni desmayes, porque el Señor tu Dios estará contigo dondequiera que vayas.'],
        ['Colosenses 2:7', 'Arraigados y sobreedificados en él, y confirmados en la fe, así como habéis sido enseñados, abundando en acciones de gracias.'],
        ['2 Timoteo 2:15', 'Procura con diligencia presentarte a Dios aprobado, como obrero que no tiene de qué avergonzarse, que usa bien la palabra de verdad.'],
        ['Marcos 10:45', 'Porque el Hijo del Hombre no vino para ser servido, sino para servir, y para dar su vida en rescate por muchos.'],
        ['Salmo 119:105', 'Lámpara es a mis pies tu palabra, y lumbrera a mi camino.'],
    ],
    'ministries' => [
        ['slug' => 'zoe-kids', 'name' => 'Zoe Kids', 'age_range' => '6 meses a 11 años', 'summary' => 'Un espacio seguro, creativo y diseñado especialmente para que descubran el amor de Dios mientras juegan y aprenden.', 'body' => 'Un lugar divertido, seguro y lleno de vida donde los más pequeños aprenden la Palabra de Dios a través de juegos, dinámicas y enseñanzas adaptadas a su edad. ¡El mejor lugar para tus hijos los domingos!', 'sort_order' => 1, 'accent' => '#f3d7b0', 'active' => true],
        ['slug' => 'zoe-teens', 'name' => 'Zoe Teens / Red H', 'age_range' => '11 a 18 años', 'summary' => 'Un ambiente dinámico y de mentoría para navegar esta etapa con identidad, propósito y fe real.', 'body' => 'Un espacio creado especialmente para adolescentes en etapa escolar. Aquí pueden hacer amigos, resolver dudas reales sobre la fe y vivir su juventud con propósito.', 'sort_order' => 2, 'accent' => '#f6c7a1', 'active' => true],
        ['slug' => 'zoe-youth', 'name' => 'Zoe Youth / Red K', 'age_range' => '18 a 28 años', 'summary' => 'Un espacio fresco y vibrante para conectar con jóvenes que comparten tu misma sintonía.', 'body' => 'Jóvenes, universitarios y profesionales jóvenes reuniéndose para conectar, conversar sobre la vida real, adorar juntos y crecer en comunidad. ¡Este es tu lugar!', 'sort_order' => 3, 'accent' => '#efb184', 'active' => true],
        ['slug' => 'redes-de-discipulado', 'name' => 'Grupos Celulares', 'age_range' => 'Redes A a la L · Jóvenes adultos', 'summary' => 'Grupos de crecimiento diseñados para acompañarte en cada etapa de tu vida adulta.', 'body' => 'Comunidades de adultos y matrimonios organizadas en redes, de la A a la L, para edificarnos mutuamente y crecer en la fe en cada etapa de la vida adulta.', 'sort_order' => 4, 'accent' => '#e8c3a4', 'active' => true],
    ],
    /*
     * Every public page and its titled sections. The structure (keys, paths,
     * menu groups and order) belongs to the code; names, menu notes, page
     * labels and section names are stored in site_pages / site_sections and
     * edited in the admin under Páginas y secciones. A page under a group
     * appears inside that group's dropdown in the menu.
     */
    'pages' => [
        ['key' => 'home', 'path' => '/', 'name' => 'Inicio', 'sections' => [
            ['key' => 'essence', 'name' => 'Por qué somos Zoe'],
            ['key' => 'cells', 'name' => 'El latido celular'],
            ['key' => 'generations', 'name' => 'Redes y ministerios'],
            ['key' => 'events', 'name' => 'Próximos eventos'],
            ['key' => 'resources', 'name' => 'Prédicas y recursos'],
            ['key' => 'visit', 'name' => 'Planifica tu visita'],
        ]],
        ['key' => 'about', 'path' => '/conocenos', 'name' => 'Conócenos', 'note' => 'Historia y pastores', 'kicker' => 'Conócenos', 'sections' => [
            ['key' => 'pastors', 'name' => 'Pastores'],
            ['key' => 'history', 'name' => '01 · Casa'],
            ['key' => 'vision', 'name' => 'Visión'],
            ['key' => 'values', 'name' => '02 · Cómo vivimos'],
            ['key' => 'first', 'name' => 'Bienvenida'],
        ]],
        ['key' => 'ministries', 'path' => '/ministerios', 'name' => 'Ministerios', 'note' => 'Cada generación', 'kicker' => 'Ministerios'],
        ['key' => 'serve', 'path' => '/involucrate', 'name' => 'Involúcrate', 'note' => 'Sirve con tus dones', 'kicker' => 'Involúcrate', 'sections' => [
            ['key' => 'why', 'name' => 'Servidores'],
            ['key' => 'areas', 'name' => 'Áreas donde puedes servir'],
            ['key' => 'teams', 'name' => 'Equipos'],
            ['key' => 'form', 'name' => 'Regístrate'],
            ['key' => 'also', 'name' => 'También en Zoe'],
        ]],
        ['key' => 'register', 'parent' => 'serve', 'path' => '/involucrate#registro', 'name' => 'Regístrate para servir', 'note' => 'Únete a un equipo'],
        ['key' => 'baptism', 'parent' => 'serve', 'path' => '/bautismos', 'name' => 'Bautismo', 'note' => 'Tu nuevo comienzo', 'kicker' => 'Bautismos', 'sections' => [
            ['key' => 'form', 'name' => 'Inscripción'],
            ['key' => 'video', 'name' => 'Antes de inscribirte'],
            ['key' => 'gallery', 'name' => 'Galería'],
        ]],
        ['key' => 'studies', 'path' => '/ruta-del-servidor', 'name' => 'Estudios'],
        ['key' => 'route', 'parent' => 'studies', 'path' => '/ruta-del-servidor', 'name' => 'La Ruta del Servidor', 'note' => 'Cinco niveles para crecer', 'kicker' => 'Estudios', 'sections' => [
            ['key' => 'levels', 'name' => 'Niveles'],
            ['key' => 'access', 'name' => 'Aula virtual'],
        ]],
        ['key' => 'classroom', 'parent' => 'studies', 'path' => '/estudios/acceso', 'name' => 'Acceso de estudiantes', 'note' => 'Notas, horario, lecturas y avisos'],
        ['key' => 'events', 'path' => '/eventos', 'name' => 'Eventos', 'note' => 'Lo que se viene', 'kicker' => 'Eventos'],
        ['key' => 'resources', 'path' => '/galeria', 'name' => 'Recursos'],
        ['key' => 'gallery', 'parent' => 'resources', 'path' => '/galeria', 'name' => 'Galería de cultos', 'note' => 'Fotos de cada servicio', 'kicker' => 'Recursos · Galería'],
        ['key' => 'devotionals', 'parent' => 'resources', 'path' => '/devocionales', 'name' => 'Devocionales', 'note' => 'Palabra para cada día', 'kicker' => 'Recursos · Devocionales'],
        ['key' => 'sermons', 'parent' => 'resources', 'path' => '/predicas', 'name' => 'Prédicas', 'note' => 'Mensajes y series', 'kicker' => 'Prédicas'],
        ['key' => 'teachings', 'parent' => 'resources', 'path' => '/recursos', 'name' => 'Enseñanzas', 'note' => 'Prédica y grupos', 'kicker' => 'Recursos', 'sections' => [
            ['key' => 'more', 'name' => 'Más recursos'],
        ]],
        ['key' => 'games', 'parent' => 'resources', 'path' => '/juegos', 'name' => 'Juegos', 'note' => 'Aprende la Biblia jugando', 'kicker' => 'Recursos · Juegos', 'sections' => [
            ['key' => 'list', 'name' => 'Juegos'],
            ['key' => 'rooms', 'name' => 'Salas en vivo'],
        ]],
        ['key' => 'radio', 'path' => '/radio', 'name' => 'Radio', 'note' => 'En vivo, las 24 horas'],
        ['key' => 'contact', 'path' => '/contacto', 'name' => 'Oración', 'note' => 'Estamos contigo', 'kicker' => 'Oración', 'sections' => [
            ['key' => 'prayer', 'name' => 'Oramos contigo'],
            ['key' => 'form', 'name' => 'Escríbenos'],
            ['key' => 'visit', 'name' => '¿Quieres conocernos en persona?'],
        ]],
        ['key' => 'give', 'path' => '/dar', 'name' => 'Dar', 'note' => 'Generosidad', 'kicker' => 'Generosidad', 'sections' => [
            ['key' => 'ways', 'name' => 'Formas de dar'],
        ]],
        ['key' => 'visit', 'path' => '/visita', 'name' => 'Planifica tu visita', 'kicker' => 'Primera vez', 'sections' => [
            ['key' => 'form', 'name' => 'Bienvenida'],
            ['key' => 'contact', 'name' => 'Visítanos'],
        ]],
    ],
    /** Áreas de servicio created on first install; from then on they are managed in the admin (Involúcrate · áreas). */
    'serve_areas' => [
        [
            'slug' => 'pastoral',
            'name' => 'Pastoral',
            'tagline' => 'Acompañando vidas, edificando fe',
            'summary' => 'Cuidamos a cada persona de la casa con oración, consejo y presencia en los momentos que más importan.',
            'body' => "El área pastoral acompaña a la iglesia en cada etapa de la vida: celebramos con quienes celebran, visitamos a quienes atraviesan una enfermedad o una pérdida y caminamos junto a cada familia con la Palabra.\n\nSi tienes un corazón dispuesto a escuchar y a orar por otros, aquí hay un lugar para ti.",
            'teams' => ['Consejería y oración', 'Visitas a hogares y hospitales', 'Seguimiento de nuevos creyentes'],
            'image_path' => '/images/pastores.jpg',
            'cta_label' => 'Pide oración',
            'cta_url' => '/contacto',
        ],
        [
            'slug' => 'ruta-del-servidor',
            'name' => 'La Ruta del Servidor',
            'tagline' => 'Formándonos para servir',
            'summary' => 'El camino de formación de Zoe: de tu encuentro con Jesús a acompañar y servir a otros en un grupo celular.',
            'body' => "La Ruta del Servidor es el proceso de estudios con el que cada persona de la casa crece paso a paso: Nueva Vida, Enraizados, Grandeza del Servicio, Discipulado y Visión Celular.\n\nEn cada nivel aprendes, sirves y te preparas para cuidar a otros con el corazón de Jesús.",
            'teams' => ['Nueva Vida', 'Enraizados', 'Grandeza del Servicio', 'Discipulado', 'Visión Celular'],
            'image_path' => '/images/ministerio-redes-de-discipulado.jpg',
            'cta_label' => 'Ver la ruta completa',
            'cta_url' => '/ruta-del-servidor',
        ],
        [
            'slug' => 'musica',
            'name' => 'Música',
            'tagline' => 'Guiamos a la casa a adorar',
            'summary' => 'Cantantes y músicos que preparan su corazón y su talento para llevar a la iglesia a la presencia de Dios en cada servicio.',
            'body' => "El equipo de música sirve con excelencia y con un corazón rendido. Ensayamos, oramos y crecemos juntos para que cada canción sea una ofrenda y cada servicio, un encuentro con Dios.\n\nSi cantas, tocas un instrumento o te apasiona el sonido, te esperamos. Te acompañamos con ensayos, formación y un equipo que se cuida como familia.",
            'teams' => ['Voces', 'Músicos', 'Sonido'],
            'image_path' => '/images/area-musica.jpg',
        ],
        [
            'slug' => 'zoe-kids',
            'name' => 'Zoe Kids',
            'tagline' => 'Sembrando la Palabra en los más pequeños',
            'summary' => 'Enseñamos a los niños de 6 meses a 11 años a conocer y amar a Jesús, con creatividad, cuidado y mucha alegría.',
            'body' => "Cada domingo, los niños de Zoe viven la Palabra con juegos, música y enseñanzas pensadas para su edad, en un espacio seguro y lleno de vida.\n\nServir en Zoe Kids es sembrar en la próxima generación. Te capacitamos y acompañamos para que enseñes con amor.",
            'teams' => ['Maestros', 'Asistentes de aula', 'Recepción de niños'],
            'image_path' => '/images/ministerio-zoe-kids.jpg',
        ],
        [
            'slug' => 'artes-escenicas',
            'name' => 'Artes Escénicas',
            'tagline' => 'El mensaje de Jesús hecho arte',
            'summary' => 'Danza, teatro y expresión creativa al servicio de la adoración y del mensaje de cada servicio y evento especial.',
            'body' => "En Artes Escénicas ponemos nuestros dones creativos al servicio del Reino. Preparamos coreografías, dramas y presentaciones que acompañan la adoración y comunican el mensaje de Jesús de una forma que toca el corazón.\n\nNo necesitas experiencia profesional: necesitas un corazón dispuesto. Ensayamos juntos, crecemos juntos y servimos con excelencia.",
            'teams' => ['Danza', 'Teatro', 'Expresión creativa'],
            'image_path' => '/images/area-artes-escenicas.jpg',
        ],
        [
            'slug' => 'visuales',
            'name' => 'Visuales',
            'tagline' => 'Llevamos el mensaje más allá de las paredes',
            'summary' => 'Multimedia, cámaras, redes, transmisión, luces y switcher: el equipo que hace que cada servicio se vea, se escuche y llegue a más personas.',
            'body' => "Visuales es el equipo técnico y creativo de la casa. Proyectamos las letras y los versículos, operamos las cámaras, dirigimos la transmisión en vivo, diseñamos la iluminación y compartimos lo que Dios hace en nuestras redes.\n\nSi te apasiona la tecnología, el diseño o el video, aquí tus dones bendicen a cientos de personas cada semana. Te capacitamos en cada puesto.",
            'teams' => ['Multimedia', 'Cámara', 'Redes', 'Transmisión', 'Luces', 'Switcher'],
            'image_path' => '/images/area-visuales.jpg',
        ],
        [
            'slug' => 'atmosfera',
            'name' => 'Atmósfera',
            'tagline' => 'Cada detalle prepara un encuentro',
            'summary' => 'Recibimos, cuidamos y preparamos la casa para que cada persona se sienta esperada desde que cruza la puerta.',
            'body' => "Atmósfera es el equipo que hace posible que cada servicio fluya: ujieres que reciben y acomodan, seguridad que cuida a la familia, mantenimiento y decoración que preparan cada espacio y contacto que da la bienvenida a quienes llegan por primera vez.\n\nSi te gusta servir con excelencia en los detalles y hacer sentir a otros en casa, este es tu equipo.",
            'teams' => ['Ujieres', 'Seguridad', 'Mantenimiento', 'Decoración', 'Contacto'],
            'image_path' => '/images/area-atmosfera.jpg',
        ],
    ],
];
