<?php

return [
    'admin_capabilities' => [
        'manageMembers' => false,
        'viewOfferings' => false,
        'viewCellActivity' => true,
        'manageMedia' => true,
        'manageContent' => true,
        'manageCells' => true,
        'manageUsers' => true,
        'manageGenerosity' => true,
    ],
    'settings' => [
        'heroTitle' => 'Tu iglesia local, donde la atmósfera de Dios se manifiesta en amor',
        'heroSubtitle' => 'Somos creyentes de Jesús y embajadores de él. Ven y forma parte de un reino que vive en abundancia.',
        'city' => 'Chiclayo, Lambayeque',
        'address' => 'Calle Bolívar 755, Chiclayo',
        'sunday' => 'Domingos 10:00 a.m.',
        'wednesday' => 'Miércoles 8:00 p.m.',
        'pastor' => 'Alberto Dávila Camacho',
        'pastorsLabel' => 'Pastores Alberto y Kelly Dávila',
        'aboutQuote' => 'Somos creyentes de Jesús y embajadores de él. Ven y forma parte de un reino que vive en abundancia.',
        'aboutText' => 'Somos una comunidad en Chiclayo, departamento de Lambayeque en Perú, y nos une la fe en Dios Padre, Dios Hijo y el Espíritu Santo. Reconocemos haber recibido provisión de Dios siendo pastoreados con amor.',
        'vision' => 'Ver vidas transformadas por Jesús en cada casa, cada generación y cada rincón de nuestra ciudad. Una iglesia local donde el amor de Dios se vuelve visible.',
        'history' => 'Iglesia Cristiana Zoe nació en Chiclayo como una familia de fe. Crecemos en células —nuestros grupos celulares— y en los servicios de la congregación, formando discípulos que llevan el amor de Cristo a su casa, su campus y su trabajo.',
        'values' => [
            ['title' => 'Amor', 'text' => 'El amor de Dios es la atmósfera de nuestra casa. Recibimos a cada persona con dignidad.'],
            ['title' => 'Palabra', 'text' => 'La Escritura guía nuestra fe, nuestros hogares y la manera en que servimos.'],
            ['title' => 'Comunidad', 'text' => 'Nadie crece solo. Las células y los ministerios son el lugar donde la fe se hace familia.'],
            ['title' => 'Generosidad', 'text' => 'Dar es adoración. Sostenemos la obra y alcanzamos a quienes más lo necesitan.'],
        ],
        'facebook' => 'https://www.facebook.com/iglesiacristianazoe',
        'youtube' => 'https://www.youtube.com/@iglesiacristianazoe6279',
        'instagram' => 'https://www.instagram.com/iglesiacristianazoe/',
        'tiktok' => 'https://www.tiktok.com/@iglesiacristianazoe',
        'messengerUrl' => 'https://m.me/iglesiacristianazoe',
        'liveUrl' => '',
        'mapUrl' => 'https://www.google.com/maps/search/?api=1&query=Calle+Bolivar+755+Chiclayo',
        'liveYoutubeId' => '',
        'serviceDayMain' => '0',
        'serviceDayWeek' => '3',
        'prayerTopics' => ['Salud', 'Familia', 'Trabajo y finanzas', 'Vida espiritual', 'Estudios', 'Gratitud', 'Otro'],
        'copy' => [],
        'bankSoles' => '3052651989073',
        'bankSolesCci' => '00230500265198907310',
        'bankDollars' => '',
        'bankDollarsCci' => '',
        'bankHolder' => 'Iglesia Cristiana de Fe Zoe',
        'yape' => '',
        'yapeHolder' => 'Iglesia Cristiana de Fe Zoe',
        'yapeQr' => '/images/yape-qr.png',
        'cardUrl' => '',
        'phone' => '(074) 252525',
        'whatsapp' => '',
        'email' => 'iglesiacristianazoe@gmail.com',
        'headingColor' => '#2A2623',
        'bodyColor' => '#6F6A64',
        'accentColor' => '#C45C26',
        'paperColor' => '#F7F4EF',
        'stoneColor' => '#E4DFD6',
        'clayColor' => '#E8D0C2',
        'fontPair' => 'mixed',
        'visitCta' => 'Planifica tu visita',
        'sermonsCta' => 'Ver prédicas',
        'baptismCta' => '¡Quiero bautizarme!',
        'railTitle' => 'Somos una iglesia que está en movimiento',
        'railText' => 'Contribuimos con nuestra ciudad. Llevamos esperanza, fe y el mensaje de Jesús a cada persona.',
        'ctaVisitTitle' => 'Planifica tu visita',
        'ctaVisitText' => 'Te esperamos. Cuéntanos que vienes y te recibimos.',
        'ctaBaptismTitle' => 'Tu nuevo comienzo',
        'ctaBaptismText' => 'El bautismo es el siguiente paso público de tu fe.',
        'ctaPrayerTitle' => 'Podemos orar por ti',
        'ctaPrayerText' => 'Escribe tu petición. Queremos acompañarte.',
        'homeFamilyKicker' => 'La casa',
        'homeFamilyTitle' => 'Una familia que se reúne cada semana.',
        'homeMinistriesTitle' => 'Elige tu lugar.',
        'footerTagline' => 'Una familia en Chiclayo, donde el amor de Dios se hace casa.',
        'aboutKicker' => 'Conócenos',
        'aboutTitle' => 'Una iglesia local, una sola familia.',
        'aboutValuesTitle' => 'Lo que nos sostiene.',
        'aboutValuesText' => 'Estos valores no son un lema. Son la manera en que pastoreamos, nos reunimos y servimos a Chiclayo.',
        'ministriesTitle' => 'Un lugar para cada etapa de la vida.',
        'ministriesText' => 'Desde los niños hasta los matrimonios, hay una comunidad donde puedes pertenecer, crecer y servir.',
        'baptismTitle' => 'Tu nuevo comienzo',
        'baptismLead' => 'Da el siguiente paso en tu fe.',
        'baptismBody' => 'Creemos que el bautismo en agua es una declaración pública de tu fe en Jesucristo. Es el símbolo de dejar atrás la vieja manera de vivir y nacer a una nueva vida en Él. Si has tomado la decisión de seguir a Jesús, este es el siguiente paso más importante que puedes dar.',
        'baptismDateLabel' => 'Próxima fecha',
        'baptismRequirementLabel' => 'Requisito',
        'baptismRequirement' => 'Asistir a la charla informativa previa.',
        'baptismDateFallback' => 'Fecha por confirmar',
        'visitTitle' => 'Planifica tu visita',
        'visitText' => 'Nos encantaría recibirte. Llena este formulario y un equipo de bienvenida estará atento para acompañarte.',
        'contactTitle' => 'Estamos para acompañarte.',
        'prayerTitle' => 'Petición de oración',
        'giveTitle' => 'Generosidad que transforma vidas',
        'giveLead' => 'Sé parte de lo que Dios está haciendo en nuestra iglesia y comunidad.',
        'giveBody' => 'Creemos que dar es un acto de adoración, gratitud y obediencia a Dios. Gracias a tu generosidad y fidelidad, podemos seguir llevando el mensaje de amor, sosteniendo la obra de la iglesia y ayudando a quienes más lo necesitan.',
        'giveYapeText' => 'Envía tu aporte al número de la iglesia o pregunta en recepción.',
        'giveCardText' => 'Aporta en línea con la pasarela de pagos de la iglesia.',
        'sermonsTitle' => 'En vivo y mensajes',
        'sermonsEmpty' => 'La transmisión se publica aquí cada servicio.',
    ],
    'weekly_notice' => [
        'enabled' => true,
        'kicker' => 'Indicaciones de la semana',
        'title' => 'Antes de reunirte con tu grupo',
        'period' => '',
        'intro' => 'Querido servidor, gracias por cuidar de tu grupo celular. Estos son los puntos que debes tener en cuenta esta semana.',
        'points' => [
            ['title' => 'Envía tu informe a tiempo', 'text' => 'Registra el informe de tu grupo CEREAL a más tardar el domingo a las 11:59 p. m., con asistencia, ofrenda y fotos de la reunión.'],
            ['title' => 'Prepara el tema con anticipación', 'text' => 'Descarga el tema de la semana desde «Temas de célula» y dedícale un tiempo de oración antes de compartirlo.'],
            ['title' => 'Ofrendas y diezmos', 'text' => 'Anota los montos exactos recibidos y entrégalos a tu servidor de red el domingo durante el servicio.'],
            ['title' => 'Fotos de la reunión', 'text' => 'Sube al menos una foto clara donde se vea al grupo reunido.'],
            ['title' => 'Acompaña a los nuevos', 'text' => 'Si llegó alguien por primera vez, regístralo como integrante y escríbele durante la semana para darle la bienvenida.'],
        ],
        'closing' => 'Equipo pastoral · Iglesia Cristiana Zoe',
    ],
    'ministries' => [
        ['slug' => 'zoe-kids', 'name' => 'Zoe Kids', 'age_range' => 'Hasta los 11 años', 'summary' => 'Ambiente seguro y dinámico para niños.', 'body' => 'Un lugar divertido, seguro y lleno de vida donde los más pequeños aprenden la Palabra de Dios a través de juegos, dinámicas y enseñanzas adaptadas a su edad. ¡El mejor lugar para tus hijos los domingos!', 'sort_order' => 1, 'accent' => '#f3d7b0', 'active' => true],
        ['slug' => 'zoe-teens', 'name' => 'Zoe Teens', 'age_range' => 'De 12 a 18 años', 'summary' => 'Espacio para adolescentes y etapa escolar.', 'body' => 'Un espacio creado especialmente para adolescentes en etapa escolar. Aquí pueden hacer amigos, resolver dudas reales sobre la fe y vivir su juventud con propósito.', 'sort_order' => 2, 'accent' => '#f6c7a1', 'active' => true],
        ['slug' => 'zoe-young', 'name' => 'Zoe Young', 'age_range' => 'De 18 a 28 años', 'summary' => 'Jóvenes y universitarios.', 'body' => 'Jóvenes, universitarios y profesionales jóvenes reuniéndose para conectar, debatir temas de la vida real, adorar juntos y crecer en comunidad. ¡Este es tu lugar!', 'sort_order' => 3, 'accent' => '#efb184', 'active' => true],
        ['slug' => 'grupos-28', 'name' => 'Grupos 28+', 'age_range' => 'De 28 años en adelante', 'summary' => 'Adultos y matrimonios.', 'body' => 'Comunidades orientadas a adultos y matrimonios en etapas de desarrollo profesional, familiar y espiritual más maduras. Un espacio para edificarnos mutuamente y crecer en la fe.', 'sort_order' => 4, 'accent' => '#e8c3a4', 'active' => true],
    ],
];
