<?php

return [
    /*
     * Administrators and the superadmin sign in only on these hosts; servers
     * (célula, hijo, red) sign in on the church site.
     */
    'admin_hosts' => array_values(array_filter(array_map(
        fn ($host) => strtolower(trim($host)),
        explode(',', (string) env('ZOE_ADMIN_HOSTS', 'admi-iglesiazoe.miacademiapreu.com,admin.localhost')),
    ))),
    'site_url' => rtrim((string) env('ZOE_SITE_URL', 'https://iglesiacristianazoe.miacademiapreu.com'), '/'),
    'admin_url' => rtrim((string) env('ZOE_ADMIN_URL', 'https://admi-iglesiazoe.miacademiapreu.com'), '/'),

    'admin_capabilities' => [
        'manageMembers' => false,
        'viewOfferings' => false,
        'viewCellActivity' => true,
        'manageMedia' => true,
        'manageContent' => true,
        'manageCells' => true,
        'manageUsers' => true,
        'manageGenerosity' => true,
    ],
    'settings' => [
        'heroTitle' => 'Vida en abundancia para ti y los tuyos.',
        'heroSubtitle' => 'No importa por dónde hayas pasado ni cuál sea tu historia. Este es un espacio seguro para conectar con Dios, con otros y empezar de nuevo. Bienvenido a casa.',
        'essenceTitle' => 'El origen de nuestro nombre',
        'essenceText' => "Hace más de 30 años nació una convicción que hoy define todo lo que somos: Cristo no solo vino a darnos salvación, vino a entregarnos su propia vida.\n\nFrente a una sociedad golpeada por la depresión, la ansiedad y la incertidumbre, nuestra certeza es absoluta: si lo tienes a Él, lo tienes todo. No estás llamado a vivir en la escasez, sino a experimentar plenitud en todas las áreas: personal, familiar, económica y espiritual. Más que una congregación, somos una familia.",
        'cellsTitle' => 'Nadie camina solo en Zoe',
        'cellsText' => "Creemos que la fe no se vive en solitario ni se limita a cuatro paredes una vez por semana. Nuestro verdadero latido sucede en las casas.\n\nCada semana nos reunimos en grupos pequeños para compartir la palabra, orar los unos por los otros, cenar y sostenernos en comunidad. Aquí nadie es un número; aquí encuentras un verdadero hogar.",
        'cellsCta' => 'Encuentra un grupo en tu zona',
        'generationsTitle' => 'Un lugar para cada generación',
        'resourcesTitle' => 'Palabra para tu semana',
        'resourcesText' => 'Mira los mensajes más recientes y vuelve a ellos cuando los necesites.',
        'visitInviteTitle' => '¿Nos acompañas este domingo?',
        'visitInviteText' => 'Queremos conocerte y recibirte como en casa. Ven a celebrar, cantar y vivir un tiempo juntos.',
        'city' => 'Chiclayo, Lambayeque',
        'address' => 'Simón Bolívar 750, Chiclayo',
        'sunday' => 'Domingos 10:00 a.m.',
        'wednesday' => 'Miércoles 8:00 p.m.',
        'pastorsLabel' => 'Pastores Alberto y Kelly Dávila',
        'aboutQuote' => 'Somos creyentes de Jesús y embajadores de él. Ven y forma parte de un reino que vive en abundancia.',
        'aboutText' => 'Somos una comunidad en Chiclayo, departamento de Lambayeque en Perú, y nos une la fe en Dios Padre, Dios Hijo y el Espíritu Santo. Reconocemos haber recibido provisión de Dios siendo pastoreados con amor.',
        'vision' => 'Ver vidas transformadas por Jesús en cada casa, cada generación y cada rincón de nuestra ciudad. Una iglesia local donde el amor de Dios se vuelve visible.',
        'history' => 'Iglesia Cristiana Zoe nació en Chiclayo como una familia de fe. Crecemos en células —nuestros grupos celulares— y en los servicios de la congregación, formando discípulos que llevan el amor de Cristo a su casa, su campus y su trabajo.',
        'values' => [
            ['title' => 'Amor', 'text' => 'El amor de Dios es la atmósfera de nuestra casa. Recibimos a cada persona con dignidad.'],
            ['title' => 'Palabra', 'text' => 'La Escritura guía nuestra fe, nuestros hogares y la manera en que servimos.'],
            ['title' => 'Comunidad', 'text' => 'Nadie crece solo. Las células y los ministerios son el lugar donde la fe se hace familia.'],
            ['title' => 'Generosidad', 'text' => 'Dar es adoración. Sostenemos la obra y alcanzamos a quienes más lo necesitan.'],
        ],
        'facebook' => 'https://www.facebook.com/iglesiacristianazoe',
        'youtube' => 'https://www.youtube.com/@iglesiacristianazoe6279',
        'instagram' => 'https://www.instagram.com/iglesiacristianazoe/',
        'tiktok' => 'https://www.tiktok.com/@iglesiacristianazoe',
        'messengerUrl' => 'https://m.me/iglesiacristianazoe',
        'liveUrl' => '',
        'mapUrl' => 'https://maps.app.goo.gl/AR25odttLqLoUrS18',
        'liveYoutubeId' => '',
        'serviceDayMain' => '0',
        'serviceDayWeek' => '3',
        'prayerTopics' => ['Salud', 'Familia', 'Trabajo y finanzas', 'Vida espiritual', 'Estudios', 'Gratitud', 'Otro'],
        'copy' => [],
        'bankSoles' => '3052651989073',
        'bankSolesCci' => '00230500265198907310',
        'bankDollars' => '',
        'bankDollarsCci' => '',
        'bankHolder' => 'Iglesia Cristiana de Fe Zoe',
        'yape' => '',
        'yapeHolder' => 'Iglesia Cristiana de Fe Zoe',
        'yapeQr' => '/images/yape-qr.png',
        'cardUrl' => '',
        'phone' => '(074) 252525',
        'whatsapp' => '',
        'email' => 'iglesiacristianazoe@gmail.com',
        'headingColor' => '#1A1A1A',
        'bodyColor' => '#5C5853',
        'accentColor' => '#C14A09',
        'paperColor' => '#FDFCFA',
        'stoneColor' => '#EBE4DA',
        'clayColor' => '#EAD8C9',
        'fontPair' => 'mixed',
        'visitCta' => 'Planifica tu visita',
        'baptismCta' => '¡Quiero bautizarme!',
        'footerTagline' => 'Una familia en Chiclayo, donde el amor de Dios se hace casa.',
        'aboutKicker' => 'Conócenos',
        'aboutTitle' => 'Una iglesia local, una sola familia.',
        'aboutValuesTitle' => 'Lo que nos sostiene.',
        'aboutValuesText' => 'Estos valores no son un lema. Son la manera en que pastoreamos, nos reunimos y servimos a Chiclayo.',
        'ministriesTitle' => 'Un lugar para cada etapa de la vida.',
        'ministriesText' => 'Desde los niños hasta los matrimonios, hay una comunidad donde puedes pertenecer, crecer y servir.',
        'baptismTitle' => 'Tu nuevo comienzo',
        'baptismLead' => 'Da el siguiente paso en tu fe.',
        'baptismBody' => 'Creemos que el bautismo en agua es una declaración pública de tu fe en Jesucristo. Es el símbolo de dejar atrás la vieja manera de vivir y nacer a una nueva vida en Él. Si has tomado la decisión de seguir a Jesús, este es el siguiente paso más importante que puedes dar.',
        'baptismDateLabel' => 'Próxima fecha',
        'baptismRequirementLabel' => 'Requisito',
        'baptismRequirement' => 'Asistir a la charla informativa previa.',
        'baptismDateFallback' => 'Fecha por confirmar',
        'visitTitle' => 'Planifica tu visita',
        'visitText' => 'Nos encantaría recibirte. Llena este formulario y un equipo de bienvenida estará atento para acompañarte.',
        'contactTitle' => 'Estamos para acompañarte.',
        'prayerTitle' => 'Petición de oración',
        'giveTitle' => 'Generosidad que transforma vidas',
        'giveLead' => 'Sé parte de lo que Dios está haciendo en nuestra iglesia y comunidad.',
        'giveBody' => 'Dar es adoración. Tu generosidad sostiene la obra y alcanza a quienes más lo necesitan.',
        'giveYapeText' => 'Escanea el código o envía tu aporte al número de la iglesia.',
        'giveCardText' => 'Aporta en línea con la pasarela de pagos de la iglesia.',
        'giveAbroadText' => 'Si vives fuera del Perú, envía tu ofrenda por transferencia internacional a nuestra cuenta del BCP con el código SWIFT. Luego escríbenos para confirmar tu aporte.',
        'bankSwift' => 'BCPLPEPL',
        'baptismVideo' => '',
        'baptismVideoTitle' => '¿Qué es el bautismo?',
        'baptismVideoText' => 'Nuestros pastores te explican en pocos minutos qué significa bautizarte y cómo prepararte.',
        'eventsTitle' => 'Lo que se viene en la casa',
        'eventsText' => 'Celebraciones, retiros y encuentros para vivir en familia.',
        'teachingsTitle' => 'Palabra para llevar a casa',
        'teachingsText' => 'La enseñanza de cada prédica y el material de los GC, listos para repasar y compartir.',
        'serveTitle' => 'Hay un lugar para ti',
        'serveText' => 'Servir es un privilegio y una expresión de nuestro amor por Dios y por las personas. Descubre el área donde tus dones bendicen a otros y únete a un equipo.',
        'serveRailTitle' => 'Somos una iglesia que *está en movimiento*',
        'serveRailText' => 'Contribuimos con nuestro país. Llevamos esperanza, fe y el mensaje de Jesús a cada persona.',
        'routeTitle' => 'Ruta del servidor',
        'routeText' => 'El camino de formación de Zoe: paso a paso, desde tu encuentro con Jesús hasta servir y acompañar a otros en un grupo celular.',
        'routeLevels' => [
            ['title' => 'Encuentro', 'text' => 'Conoces a Jesús, sanas tu historia y das tus primeros pasos en la casa.'],
            ['title' => 'Discipulado', 'text' => 'Construyes bases firmes en la Palabra, la oración y la vida en comunidad.'],
            ['title' => 'Liderazgo', 'text' => 'Aprendes a cuidar y acompañar a otros dentro de un grupo celular.'],
            ['title' => 'Servidor', 'text' => 'Recibes tu grupo y comienzas a servir como servidor de célula.'],
        ],
        'sermonsTitle' => 'En vivo y mensajes',
        'sermonsEmpty' => 'La transmisión se publica aquí cada servicio.',
    ],
    'weekly_notice' => [
        'enabled' => true,
        'kicker' => 'Indicaciones de la semana',
        'title' => 'Antes de reunirte con tu grupo',
        'period' => '',
        'intro' => 'Querido servidor, gracias por cuidar de tu grupo celular. Estos son los puntos que debes tener en cuenta esta semana.',
        'points' => [
            ['title' => 'Envía tu informe a tiempo', 'text' => 'Registra el informe de tu grupo CEREAL a más tardar el domingo a las 11:59 p. m., con asistencia, ofrenda y fotos de la reunión.'],
            ['title' => 'Prepara el tema con anticipación', 'text' => 'Descarga el tema de la semana desde «Temas de célula» y dedícale un tiempo de oración antes de compartirlo.'],
            ['title' => 'Ofrendas y diezmos', 'text' => 'Anota los montos exactos recibidos y entrégalos a tu servidor de red el domingo durante el servicio.'],
            ['title' => 'Fotos de la reunión', 'text' => 'Sube al menos una foto clara donde se vea al grupo reunido.'],
            ['title' => 'Acompaña a los nuevos', 'text' => 'Si llegó alguien por primera vez, regístralo como integrante y escríbele durante la semana para darle la bienvenida.'],
        ],
        'closing' => 'Equipo pastoral · Iglesia Cristiana Zoe',
    ],
    'ministries' => [
        ['slug' => 'zoe-kids', 'name' => 'Zoe Kids', 'age_range' => '6 meses a 11 años', 'summary' => 'Un espacio seguro, creativo y diseñado especialmente para que descubran el amor de Dios mientras juegan y aprenden.', 'body' => 'Un lugar divertido, seguro y lleno de vida donde los más pequeños aprenden la Palabra de Dios a través de juegos, dinámicas y enseñanzas adaptadas a su edad. ¡El mejor lugar para tus hijos los domingos!', 'sort_order' => 1, 'accent' => '#f3d7b0', 'active' => true],
        ['slug' => 'zoe-teens', 'name' => 'Zoe Teens / Red H', 'age_range' => '11 a 18 años', 'summary' => 'Un ambiente dinámico y de mentoría para navegar esta etapa con identidad, propósito y fe real.', 'body' => 'Un espacio creado especialmente para adolescentes en etapa escolar. Aquí pueden hacer amigos, resolver dudas reales sobre la fe y vivir su juventud con propósito.', 'sort_order' => 2, 'accent' => '#f6c7a1', 'active' => true],
        ['slug' => 'zoe-youth', 'name' => 'Zoe Youth / Red K', 'age_range' => '18 a 28 años', 'summary' => 'Un espacio fresco y vibrante para conectar con jóvenes que comparten tu misma sintonía.', 'body' => 'Jóvenes, universitarios y profesionales jóvenes reuniéndose para conectar, conversar sobre la vida real, adorar juntos y crecer en comunidad. ¡Este es tu lugar!', 'sort_order' => 3, 'accent' => '#efb184', 'active' => true],
        ['slug' => 'redes-de-discipulado', 'name' => 'Redes de Discipulado', 'age_range' => 'Redes A a la L · Jóvenes adultos', 'summary' => 'Grupos de crecimiento diseñados para acompañarte en cada etapa de tu vida adulta.', 'body' => 'Comunidades de adultos y matrimonios organizadas en redes, de la A a la L, para edificarnos mutuamente y crecer en la fe en cada etapa de la vida adulta.', 'sort_order' => 4, 'accent' => '#e8c3a4', 'active' => true],
    ],
    /** Áreas de servicio created on first install; from then on they are managed in the admin (Involúcrate · áreas). */
    'serve_areas' => [
        [
            'slug' => 'pastoral',
            'name' => 'Pastoral',
            'tagline' => 'Acompañando vidas, edificando fe',
            'summary' => 'Cuidamos a cada persona de la casa con oración, consejo y presencia en los momentos que más importan.',
            'body' => "El área pastoral acompaña a la iglesia en cada etapa de la vida: celebramos con quienes celebran, visitamos a quienes atraviesan una enfermedad o una pérdida y caminamos junto a cada familia con la Palabra.\n\nSi tienes un corazón dispuesto a escuchar y a orar por otros, aquí hay un lugar para ti.",
            'teams' => ['Consejería y oración', 'Visitas a hogares y hospitales', 'Seguimiento de nuevos creyentes'],
            'image_path' => '/images/pastores.jpg',
        ],
        [
            'slug' => 'ruta-del-servidor',
            'name' => 'La Ruta del Servidor',
            'tagline' => 'Formándonos para servir',
            'summary' => 'El camino de formación de Zoe: de tu encuentro con Jesús a acompañar y servir a otros en un grupo celular.',
            'body' => "La Ruta del Servidor es el proceso con el que cada persona de la casa crece paso a paso: Encuentro, Discipulado, Liderazgo y Servidor.\n\nEn cada nivel aprendes, sirves y te preparas para cuidar a otros con el corazón de Jesús.",
            'teams' => ['Encuentro', 'Discipulado', 'Liderazgo', 'Servidor'],
            'image_path' => '/images/ministerio-redes-de-discipulado.jpg',
            'cta_label' => 'Ver la ruta completa',
            'cta_url' => '/ruta-del-servidor',
        ],
        [
            'slug' => 'atmosfera',
            'name' => 'Atmósfera',
            'tagline' => 'Cada detalle prepara un encuentro',
            'summary' => 'Preparamos la casa para que cada persona se sienta esperada: recibimos, ordenamos y creamos el ambiente de cada servicio.',
            'body' => "Atmósfera es el equipo que hace posible que cada servicio fluya: ujieres que reciben y acomodan, visuales que acompañan la adoración y multimedia que lleva el mensaje más allá de las paredes de la iglesia.\n\nSi te gusta servir con excelencia en los detalles, este es tu equipo.",
            'teams' => ['Ujieres', 'Visuales', 'Multimedia'],
            'image_path' => '/images/banner8.jpg',
        ],
        [
            'slug' => 'zoe-kids',
            'name' => 'Zoe Kids',
            'tagline' => 'Sembrando la Palabra en los más pequeños',
            'summary' => 'Enseñamos a los niños de 6 meses a 11 años a conocer y amar a Jesús, con creatividad, cuidado y mucha alegría.',
            'body' => "Cada domingo, los niños de Zoe viven la Palabra con juegos, música y enseñanzas pensadas para su edad, en un espacio seguro y lleno de vida.\n\nServir en Zoe Kids es sembrar en la próxima generación. Te capacitamos y acompañamos para que enseñes con amor.",
            'teams' => ['Maestros', 'Asistentes de aula', 'Recepción de niños'],
            'image_path' => '/images/ministerio-zoe-kids.jpg',
        ],
        [
            'slug' => 'alabanza',
            'name' => 'Alabanza',
            'tagline' => 'Guiamos a la casa a adorar',
            'summary' => 'Músicos, cantantes y técnicos que preparan su corazón y su talento para llevar a la iglesia a la presencia de Dios.',
            'body' => "El equipo de alabanza sirve con excelencia y con un corazón rendido. Ensayamos, oramos y crecemos juntos para que cada canción sea una ofrenda.\n\nSi cantas, tocas un instrumento o te apasiona el sonido, te esperamos.",
            'teams' => ['Voces', 'Músicos', 'Sonido'],
            'image_path' => '/images/banner4.jpg',
        ],
        [
            'slug' => 'bienvenida',
            'name' => 'Bienvenida',
            'tagline' => 'El primer rostro de la casa',
            'summary' => 'Recibimos a quienes llegan por primera vez, los acompañamos durante el servicio y los conectamos con la familia de Zoe.',
            'body' => "Una sonrisa y un saludo pueden cambiar el día de alguien. El equipo de bienvenida recibe a cada visitante, resuelve sus dudas y lo acompaña hasta que encuentra su lugar en un grupo celular.\n\nSi te gusta conocer personas y hacerlas sentir en casa, aquí perteneces.",
            'teams' => ['Recepción', 'Consolidación'],
            'image_path' => '/images/familia1.jpg',
        ],
        [
            'slug' => 'intercesion',
            'name' => 'Intercesión',
            'tagline' => 'Sosteniendo la casa en oración',
            'summary' => 'Oramos por la iglesia, por la ciudad y por cada petición que llega, antes, durante y después de cada servicio.',
            'body' => "La intercesión es el motor silencioso de la iglesia. Nos reunimos para orar por los pastores, por cada servicio, por las familias y por cada petición que recibimos.\n\nSi Dios ha puesto en ti una carga por orar, únete a este equipo.",
            'teams' => ['Oración antes del servicio', 'Peticiones de oración'],
            'image_path' => '/images/vida-en-casas.jpg',
        ],
    ],
];
