<?php

namespace App\Domain\Radio\Catalog;

/**
 * The music genres (musical styles) the radio library starts with, grouped in families.
 *
 * Each genre lists the names music databases give it (MusicBrainz, Wikidata, iTunes, Deezer),
 * in English and Spanish, so a tag found on the internet lands on the right Spanish genre.
 */
final class Genres
{
    public const FAMILIES = [
        'cristiana' => 'Música cristiana',
        'pop' => 'Pop',
        'rock' => 'Rock',
        'metal' => 'Metal y punk',
        'urbano' => 'Urbano y hip hop',
        'electronica' => 'Electrónica',
        'tropical' => 'Tropical y caribeña',
        'regional' => 'Regional mexicano',
        'latina' => 'Latinoamericana y folclore',
        'jazz' => 'Jazz, blues y soul',
        'clasica' => 'Clásica e instrumental',
        'otros' => 'Del mundo y otros',
    ];

    /**
     * The Christian version of a secular genre: a reggaeton song of a Christian artist is Christian reggaeton.
     *
     * @var array<string, string>
     */
    public const CHRISTIAN = [
        'Pop' => 'Pop cristiano',
        'Pop latino' => 'Pop cristiano',
        'Pop rock' => 'Pop rock cristiano',
        'Rock' => 'Rock cristiano',
        'Rock en español' => 'Rock cristiano',
        'Hard rock' => 'Rock cristiano',
        'Rock alternativo' => 'Rock alternativo cristiano',
        'Indie rock' => 'Indie cristiano',
        'Indie pop' => 'Indie cristiano',
        'Heavy metal' => 'Metal cristiano',
        'Metal alternativo' => 'Metal cristiano',
        'Punk rock' => 'Punk cristiano',
        'Hardcore punk' => 'Hardcore cristiano',
        'Hip hop' => 'Rap cristiano',
        'Rap' => 'Rap cristiano',
        'Hip hop latino' => 'Rap cristiano',
        'Rap en español' => 'Rap cristiano',
        'Reguetón' => 'Reguetón cristiano',
        'Dembow' => 'Reguetón cristiano',
        'Trap' => 'Trap cristiano',
        'Trap latino' => 'Trap cristiano',
        'Urbano latino' => 'Urbano cristiano',
        'Electrónica' => 'Electrónica cristiana',
        'EDM' => 'Electrónica cristiana',
        'Balada' => 'Balada cristiana',
        'Balada romántica' => 'Balada cristiana',
        'Salsa' => 'Salsa cristiana',
        'Cumbia' => 'Cumbia cristiana',
        'Bachata' => 'Bachata cristiana',
        'Merengue' => 'Merengue cristiano',
        'Regional mexicano' => 'Regional mexicano cristiano',
        'Folk' => 'Folk cristiano',
        'Country' => 'Country cristiano',
        'Instrumental' => 'Instrumental cristiano',
        'Música infantil' => 'Música cristiana infantil',
    ];

    /**
     * Every genre, by family: [name, [other names it goes by]].
     *
     * @return array<string, list<array{0: string, 1: list<string>}>>
     */
    public static function all(): array
    {
        return [
            'cristiana' => [
                ['Música cristiana', ['christian', 'christian music', 'christian & gospel', 'religious', 'religiosa', 'cristiana', 'cristiano', 'musica cristiana', 'inspirational', 'gospel & religious', 'latin christian', 'christian latin']],
                ['Adoración', ['worship', 'worship music', 'christian worship', 'contemporary worship music', 'contemporary worship', 'praise & worship', 'praise and worship', 'alabanza y adoracion', 'adoracion', 'latin worship']],
                ['Alabanza', ['praise', 'praise music', 'alabanza', 'alabanzas', 'jubilo']],
                ['Cristiana contemporánea (CCM)', ['contemporary christian', 'contemporary christian music', 'ccm', 'christian contemporary', 'adult contemporary christian']],
                ['Pop cristiano', ['christian pop', 'pop cristiano', 'gospel pop']],
                ['Pop rock cristiano', ['christian pop rock', 'christian pop/rock']],
                ['Rock cristiano', ['christian rock', 'rock cristiano', 'jesus rock']],
                ['Rock alternativo cristiano', ['christian alternative rock', 'christian alternative', 'christian alt rock']],
                ['Indie cristiano', ['christian indie', 'christian indie rock', 'christian indie pop']],
                ['Metal cristiano', ['christian metal', 'unblack metal', 'white metal', 'christian heavy metal']],
                ['Punk cristiano', ['christian punk']],
                ['Hardcore cristiano', ['christian hardcore', 'christian metalcore']],
                ['Rap cristiano', ['christian hip hop', 'christian rap', 'holy hip hop', 'gospel rap', 'gospel hip hop', 'rap cristiano', 'hip hop cristiano', 'christian hip-hop']],
                ['Reguetón cristiano', ['christian reggaeton', 'reggaeton cristiano', 'regueton cristiano', 'christian reggaetón']],
                ['Trap cristiano', ['christian trap', 'trap cristiano']],
                ['Urbano cristiano', ['christian urban', 'urbano cristiano', 'musica urbana cristiana', 'christian latin urban']],
                ['Electrónica cristiana', ['christian electronic', 'christian edm', 'christian dance', 'christian electronic dance music']],
                ['Gospel', ['gospel', 'gospel music', 'gospel latino']],
                ['Gospel contemporáneo', ['contemporary gospel', 'urban contemporary gospel', 'modern gospel', 'urban gospel']],
                ['Gospel tradicional', ['traditional gospel', 'black gospel', 'gospel blues']],
                ['Southern gospel', ['southern gospel', 'country gospel', 'bluegrass gospel']],
                ['Coro góspel', ['gospel choir', 'mass choir', 'choir gospel']],
                ['Himnos', ['hymns', 'hymn', 'himno', 'himnos', 'himnario', 'hymnal', 'traditional hymns']],
                ['Coros cristianos', ['coritos', 'coros', 'coros cristianos', 'choruses', 'christian choruses']],
                ['Música cristiana infantil', ["christian children's music", 'christian kids', 'children christian', 'infantil cristiana', 'musica cristiana para ninos']],
                ['Balada cristiana', ['christian ballad', 'balada cristiana']],
                ['Salsa cristiana', ['christian salsa', 'salsa cristiana']],
                ['Cumbia cristiana', ['christian cumbia', 'cumbia cristiana']],
                ['Bachata cristiana', ['christian bachata', 'bachata cristiana']],
                ['Merengue cristiano', ['christian merengue', 'merengue cristiano']],
                ['Regional mexicano cristiano', ['christian regional mexican', 'regional mexicano cristiano', 'christian ranchera']],
                ['Folk cristiano', ['christian folk', 'folk cristiano']],
                ['Country cristiano', ['christian country', 'country cristiano', 'positive country']],
                ['Instrumental cristiano', ['christian instrumental', 'instrumental cristiano', 'instrumental worship']],
                ['Música católica', ['catholic', 'catholic music', 'musica catolica', 'catolica']],
                ['Música litúrgica', ['liturgical', 'liturgical music', 'mass', 'musica liturgica']],
                ['Música sacra', ['sacred music', 'sacred', 'church music', 'musica sacra', 'religious music']],
                ['Canto gregoriano', ['gregorian chant', 'plainchant', 'plainsong', 'canto gregoriano']],
                ['Espirituales negros', ['spiritual', 'spirituals', 'negro spiritual', 'african-american spiritual']],
                ['Jesus music', ['jesus music', 'jesus movement']],
                ['Adoración profética', ['prophetic worship', 'spontaneous worship', 'soaking', 'soaking music', 'adoracion profetica', 'adoracion espontanea']],
                ['Música mesiánica', ['messianic', 'messianic music', 'messianic jewish music', 'musica mesianica']],
            ],
            'pop' => [
                ['Pop', ['pop', 'pop music', 'mainstream pop']],
                ['Pop latino', ['latin pop', 'pop latino', 'pop en espanol', 'spanish pop']],
                ['Pop rock', ['pop rock', 'pop/rock', 'pop-rock']],
                ['Pop rock alternativo', ['alternative pop rock', 'alternative pop/rock', 'pop rock alternativo', 'alt pop rock']],
                ['Pop progresivo', ['progressive pop', 'prog pop', 'pop progresivo']],
                ['Pop alternativo', ['alternative pop', 'alt-pop', 'alt pop', 'pop alternativo']],
                ['Indie pop', ['indie pop', 'indie-pop']],
                ['Synth-pop', ['synth-pop', 'synthpop', 'synth pop', 'new wave']],
                ['Electropop', ['electropop', 'electro pop', 'electro-pop']],
                ['Dance pop', ['dance-pop', 'dance pop']],
                ['Teen pop', ['teen pop']],
                ['Pop acústico', ['acoustic pop', 'acoustic', 'acustico', 'pop acustico']],
                ['Power pop', ['power pop']],
                ['Dream pop', ['dream pop']],
                ['Art pop', ['art pop']],
                ['Pop barroco', ['baroque pop', 'chamber pop']],
                ['Pop adulto contemporáneo', ['adult contemporary', 'soft pop', 'adult pop']],
                ['Europop', ['europop', 'euro pop']],
                ['K-pop', ['k-pop', 'kpop', 'korean pop']],
                ['J-pop', ['j-pop', 'jpop', 'japanese pop']],
                ['Balada', ['ballad', 'balada', 'power ballad', 'pop ballad', 'latin ballad']],
                ['Balada romántica', ['romantic ballad', 'balada romantica', 'baladas romanticas', 'romantic']],
            ],
            'rock' => [
                ['Rock', ['rock', 'rock music']],
                ['Rock alternativo', ['alternative rock', 'alternative', 'alt-rock', 'alt rock', 'rock alternativo', 'modern rock']],
                ['Rock en español', ['rock en espanol', 'spanish rock', 'rock latino', 'latin rock']],
                ['Rock progresivo', ['progressive rock', 'prog rock', 'prog', 'rock progresivo', 'art rock']],
                ['Indie rock', ['indie rock', 'indie']],
                ['Hard rock', ['hard rock']],
                ['Soft rock', ['soft rock']],
                ['Rock clásico', ['classic rock', 'rock clasico']],
                ['Rock and roll', ['rock and roll', 'rock & roll', "rock 'n' roll", 'rock n roll', 'rockabilly']],
                ['Rock psicodélico', ['psychedelic rock', 'psychedelic', 'psicodelico']],
                ['Rock sinfónico', ['symphonic rock']],
                ['Folk rock', ['folk rock', 'folk-rock']],
                ['Arena rock', ['arena rock', 'stadium rock']],
                ['Rock gótico', ['gothic rock', 'goth rock', 'goth']],
                ['Rock electrónico', ['electronic rock', 'electro rock']],
                ['Blues rock', ['blues rock', 'blues-rock']],
                ['Southern rock', ['southern rock']],
                ['Rap rock', ['rap rock', 'rapcore']],
                ['Post-rock', ['post-rock', 'post rock']],
                ['Post-grunge', ['post-grunge', 'post grunge']],
                ['Grunge', ['grunge']],
                ['Emo', ['emo', 'emo pop']],
                ['Shoegaze', ['shoegaze', 'shoegazing']],
                ['Britpop', ['britpop', 'brit pop']],
            ],
            'metal' => [
                ['Heavy metal', ['heavy metal', 'metal']],
                ['Metal alternativo', ['alternative metal', 'alt metal']],
                ['Nu metal', ['nu metal', 'nu-metal']],
                ['Rap metal', ['rap metal']],
                ['Metalcore', ['metalcore']],
                ['Metal sinfónico', ['symphonic metal']],
                ['Metal progresivo', ['progressive metal', 'prog metal']],
                ['Power metal', ['power metal']],
                ['Thrash metal', ['thrash metal', 'thrash']],
                ['Death metal', ['death metal', 'melodic death metal']],
                ['Black metal', ['black metal']],
                ['Metal gótico', ['gothic metal']],
                ['Djent', ['djent']],
                ['Punk rock', ['punk rock', 'punk']],
                ['Pop punk', ['pop punk', 'pop-punk']],
                ['Hardcore punk', ['hardcore punk', 'hardcore', 'melodic hardcore']],
                ['Post-hardcore', ['post-hardcore', 'post hardcore']],
                ['Ska punk', ['ska punk', 'ska-punk']],
                ['Screamo', ['screamo']],
            ],
            'urbano' => [
                ['Reguetón', ['reggaeton', 'reggaetón', 'regueton', 'reguetón', 'reggaeton romantico', 'perreo']],
                ['Urbano latino', ['latin urban', 'urbano latino', 'musica urbana', 'urbano', 'latin urbano', 'urban latin']],
                ['Trap latino', ['latin trap', 'trap latino', 'trap en espanol']],
                ['Trap', ['trap', 'trap music', 'trap rap']],
                ['Hip hop', ['hip hop', 'hip-hop', 'hiphop', 'hip hop music']],
                ['Rap', ['rap', 'rap music']],
                ['Hip hop latino', ['latin hip hop', 'latin rap', 'rap latino', 'hip hop latino', 'latin hip-hop']],
                ['Rap en español', ['spanish hip hop', 'rap en espanol', 'rap espanol', 'spanish rap', 'hip hop en espanol']],
                ['Rap consciente', ['conscious hip hop', 'conscious rap', 'rap consciente']],
                ['Boom bap', ['boom bap', 'boom-bap']],
                ['Drill', ['drill', 'uk drill']],
                ['Grime', ['grime']],
                ['Dembow', ['dembow', 'dembow dominicano']],
                ['Moombahton', ['moombahton']],
                ['Dancehall', ['dancehall']],
                ['Afrobeats', ['afrobeats', 'afropop', 'afro pop', 'afro-pop']],
                ['R&B contemporáneo', ['contemporary r&b', 'contemporary rnb', 'urban contemporary', 'alternative r&b']],
                ['Pop urbano', ['urban pop', 'pop urbano']],
            ],
            'electronica' => [
                ['Electrónica', ['electronic', 'electronica', 'electronic music', 'electronica music']],
                ['EDM', ['edm', 'electronic dance music', 'dance', 'dance music', 'club']],
                ['House', ['house', 'house music']],
                ['Deep house', ['deep house']],
                ['Tropical house', ['tropical house']],
                ['Progressive house', ['progressive house']],
                ['Electro house', ['electro house', 'electro']],
                ['Techno', ['techno']],
                ['Trance', ['trance', 'progressive trance', 'uplifting trance']],
                ['Dubstep', ['dubstep']],
                ['Drum and bass', ['drum and bass', 'drum & bass', 'drum n bass', 'dnb', 'jungle']],
                ['Future bass', ['future bass']],
                ['Synthwave', ['synthwave', 'retrowave', 'outrun']],
                ['Chillout', ['chillout', 'chill out', 'chill', 'chillwave']],
                ['Lo-fi', ['lo-fi', 'lofi', 'lo-fi hip hop', 'lofi hip hop', 'chillhop']],
                ['Downtempo', ['downtempo']],
                ['Trip hop', ['trip hop', 'trip-hop']],
                ['Ambient', ['ambient', 'ambient music', 'dark ambient']],
            ],
            'tropical' => [
                ['Tropical', ['tropical', 'tropical latin', 'latin tropical', 'musica tropical']],
                ['Salsa', ['salsa', 'salsa dura']],
                ['Salsa romántica', ['salsa romantica', 'romantic salsa']],
                ['Merengue', ['merengue']],
                ['Bachata', ['bachata']],
                ['Cumbia', ['cumbia', 'cumbia colombiana']],
                ['Cumbia peruana', ['cumbia peruana', 'chicha', 'peruvian cumbia', 'cumbia andina']],
                ['Vallenato', ['vallenato']],
                ['Son cubano', ['son cubano', 'son', 'cuban son']],
                ['Timba', ['timba']],
                ['Mambo', ['mambo']],
                ['Chachachá', ['cha-cha-cha', 'chachacha', 'cha cha cha']],
                ['Champeta', ['champeta']],
                ['Plena', ['plena']],
                ['Bomba', ['bomba puertorriquena', 'bomba']],
                ['Kompa', ['kompa', 'compas', 'konpa']],
                ['Zouk', ['zouk']],
                ['Soca', ['soca']],
                ['Calypso', ['calypso']],
            ],
            'regional' => [
                ['Regional mexicano', ['regional mexican', 'regional mexicano', 'musica mexicana', 'mexican', 'musica regional mexicana']],
                ['Ranchera', ['ranchera', 'rancheras', 'cancion ranchera']],
                ['Mariachi', ['mariachi']],
                ['Banda', ['banda', 'banda sinaloense', 'banda music']],
                ['Norteño', ['norteno', 'norteño', 'nortena', 'musica nortena']],
                ['Corridos', ['corrido', 'corridos']],
                ['Corridos tumbados', ['corridos tumbados', 'corrido tumbado']],
                ['Sierreño', ['sierreno', 'sierreño']],
                ['Grupera', ['grupero', 'grupera', 'onda grupera']],
                ['Duranguense', ['duranguense']],
                ['Tejano', ['tejano', 'tex-mex', 'texmex']],
                ['Huapango', ['huapango', 'son huasteco']],
            ],
            'latina' => [
                ['Folclore latinoamericano', ['latin american folk', 'folklore', 'folclore', 'latin folk', 'musica folclorica', 'nueva cancion']],
                ['Música andina', ['andean', 'andean music', 'musica andina', 'andina']],
                ['Huayno', ['huayno', 'huaino', 'wayno']],
                ['Música criolla', ['musica criolla', 'criolla', 'peruvian creole music']],
                ['Vals peruano', ['peruvian waltz', 'vals peruano', 'vals criollo']],
                ['Música afroperuana', ['afro-peruvian', 'afroperuana', 'festejo', 'lando']],
                ['Marinera', ['marinera']],
                ['Bolero', ['bolero', 'boleros']],
                ['Tango', ['tango']],
                ['Samba', ['samba', 'pagode']],
                ['Bossa nova', ['bossa nova']],
                ['MPB', ['mpb', 'musica popular brasileira', 'brazilian popular music']],
                ['Forró', ['forro', 'forró']],
                ['Sertanejo', ['sertanejo', 'sertanejo universitario']],
                ['Axé', ['axe', 'axé']],
                ['Joropo', ['joropo']],
                ['Música llanera', ['musica llanera', 'llanera']],
                ['Chacarera', ['chacarera']],
                ['Zamba', ['zamba']],
                ['Cueca', ['cueca']],
                ['Nueva trova', ['nueva trova', 'trova', 'trova cubana']],
                ['Cantautor', ['singer-songwriter', 'singer/songwriter', 'cantautor', 'cancion de autor']],
            ],
            'jazz' => [
                ['Jazz', ['jazz']],
                ['Smooth jazz', ['smooth jazz']],
                ['Jazz latino', ['latin jazz', 'jazz latino', 'afro-cuban jazz']],
                ['Jazz fusión', ['jazz fusion', 'fusion', 'jazz-rock']],
                ['Swing', ['swing', 'big band']],
                ['Bebop', ['bebop', 'bop', 'hard bop']],
                ['Blues', ['blues', 'delta blues', 'chicago blues']],
                ['Soul', ['soul', 'soul music', 'southern soul']],
                ['Neo soul', ['neo soul', 'neo-soul']],
                ['R&B', ['r&b', 'rnb', 'rhythm and blues', 'r&b/soul', 'r and b']],
                ['Funk', ['funk']],
                ['Motown', ['motown']],
                ['Disco', ['disco', 'nu-disco']],
            ],
            'clasica' => [
                ['Clásica', ['classical', 'classical music', 'musica clasica', 'clasica', 'western classical music']],
                ['Barroca', ['baroque', 'baroque music', 'musica barroca']],
                ['Romanticismo', ['romantic era', 'romantic classical', 'romanticism']],
                ['Ópera', ['opera']],
                ['Coral', ['choral', 'choir', 'coral', 'choral music']],
                ['Orquestal', ['orchestral', 'orchestra', 'orquesta']],
                ['Banda sonora', ['soundtrack', 'film score', 'score', 'film soundtrack', 'banda sonora', 'video game music']],
                ['Instrumental', ['instrumental', 'instrumentals']],
                ['Piano', ['piano', 'solo piano', 'piano solo']],
                ['Neoclásica', ['neoclassical', 'modern classical', 'contemporary classical', 'neo-classical']],
                ['Música de cámara', ['chamber music', 'string quartet']],
                ['Crossover clásico', ['classical crossover', 'operatic pop', 'popera']],
                ['New age', ['new age', 'new-age']],
                ['Música para meditar', ['meditation', 'relaxation', 'healing', 'relajacion', 'meditacion', 'sleep music']],
            ],
            'otros' => [
                ['Folk', ['folk', 'folk music', 'contemporary folk']],
                ['Indie folk', ['indie folk', 'folk pop', 'folk-pop']],
                ['Country', ['country', 'country music', 'contemporary country']],
                ['Country pop', ['country pop']],
                ['Bluegrass', ['bluegrass']],
                ['Americana', ['americana', 'roots rock']],
                ['Celta', ['celtic', 'celtic music', 'irish folk']],
                ['Flamenco', ['flamenco', 'nuevo flamenco']],
                ['Rumba', ['rumba', 'rumba flamenca', 'rumba catalana']],
                ['Reggae', ['reggae', 'roots reggae']],
                ['Reggae en español', ['latin reggae', 'reggae en espanol', 'reggae latino']],
                ['Ska', ['ska']],
                ['Afrobeat', ['afrobeat']],
                ['Música del mundo', ['world', 'world music', 'worldbeat', 'musica del mundo']],
                ['Música infantil', ["children's music", 'kids', 'children', 'infantil', 'musica infantil', 'nursery rhymes']],
                ['Música navideña', ['christmas', 'christmas music', 'holiday', 'navidad', 'villancicos', 'villancico', 'christmas carols']],
                ['A capella', ['a cappella', 'acapella', 'a capella']],
                ['Palabra hablada', ['spoken word', 'poetry', 'sermon', 'predicacion', 'audiobook']],
                ['Easy listening', ['easy listening', 'lounge']],
                ['Experimental', ['experimental', 'avant-garde']],
            ],
        ];
    }
}
