<?php

namespace App\Domain\Radio\Catalog;

/**
 * The music genres (musical styles) the radio library starts with, grouped in families.
 *
 * Each genre lists the names music databases give it (MusicBrainz, Wikidata, iTunes, Deezer),
 * in English, Spanish and Portuguese, so a tag found on the internet lands on the right Spanish
 * genre. No name belongs to two genres.
 */
final class Genres
{
    public const FAMILIES = [
        'cristiana' => 'Música cristiana',
        'pop' => 'Pop',
        'rock' => 'Rock',
        'metal' => 'Metal y punk',
        'urbano' => 'Urbano y hip hop',
        'electronica' => 'Electrónica',
        'tropical' => 'Tropical y caribeña',
        'regional' => 'Regional mexicano',
        'latina' => 'Latinoamericana y folclore',
        'jazz' => 'Jazz, blues y soul',
        'clasica' => 'Clásica e instrumental',
        'otros' => 'Del mundo y otros',
    ];

    /**
     * The Christian version of a secular genre: a reggaeton song of a Christian artist is Christian reggaeton.
     *
     * @var array<string, string>
     */
    public const CHRISTIAN = [
        'Pop' => 'Pop cristiano',
        'Pop latino' => 'Pop cristiano',
        'Pop alternativo' => 'Pop cristiano',
        'Dance pop' => 'Pop cristiano',
        'Electropop' => 'Pop cristiano',
        'Teen pop' => 'Pop cristiano',
        'Pop melódico' => 'Pop cristiano',
        'Pop adulto contemporáneo' => 'Cristiana contemporánea (CCM)',
        'Pop rock' => 'Pop rock cristiano',
        'Soft rock' => 'Pop rock cristiano',
        'Synth-pop' => 'Synth-pop cristiano',
        'K-pop' => 'K-pop cristiano',
        'Pop acústico' => 'Acústico cristiano',
        'Rock' => 'Rock cristiano',
        'Rock en español' => 'Rock cristiano',
        'Hard rock' => 'Rock cristiano',
        'Post-grunge' => 'Rock cristiano',
        'Grunge' => 'Rock cristiano',
        'Rock alternativo' => 'Rock alternativo cristiano',
        'Emo' => 'Rock alternativo cristiano',
        'Indie rock' => 'Indie cristiano',
        'Indie pop' => 'Indie cristiano',
        'Heavy metal' => 'Metal cristiano',
        'Metal alternativo' => 'Metal cristiano',
        'Metal progresivo' => 'Metal cristiano',
        'Rap metal' => 'Metal cristiano',
        'Nu metal' => 'Nu metal cristiano',
        'Metalcore' => 'Metalcore cristiano',
        'Metalcore melódico' => 'Metalcore cristiano',
        'Post-hardcore' => 'Post-hardcore cristiano',
        'Deathcore' => 'Deathcore cristiano',
        'Death metal' => 'Death metal cristiano',
        'Black metal' => 'Unblack metal',
        'Power metal' => 'Power metal cristiano',
        'Metal sinfónico' => 'Metal sinfónico cristiano',
        'Thrash metal' => 'Thrash metal cristiano',
        'Punk rock' => 'Punk cristiano',
        'Pop punk' => 'Pop punk cristiano',
        'Hardcore punk' => 'Hardcore cristiano',
        'Hardcore melódico' => 'Hardcore cristiano',
        'Screamo' => 'Hardcore cristiano',
        'Ska punk' => 'Ska cristiano',
        'Hip hop' => 'Rap cristiano',
        'Rap' => 'Rap cristiano',
        'Hip hop latino' => 'Rap cristiano',
        'Rap en español' => 'Rap cristiano',
        'Rap consciente' => 'Rap cristiano',
        'Boom bap' => 'Rap cristiano',
        'Hip hop alternativo' => 'Rap cristiano',
        'Pop rap' => 'Rap cristiano',
        'Rap melódico' => 'Rap cristiano',
        'Drill' => 'Drill cristiano',
        'Reguetón' => 'Reguetón cristiano',
        'Dembow' => 'Reguetón cristiano',
        'Trap' => 'Trap cristiano',
        'Trap latino' => 'Trap cristiano',
        'Urbano latino' => 'Urbano cristiano',
        'Pop urbano' => 'Pop urbano cristiano',
        'Electrónica' => 'Electrónica cristiana',
        'EDM' => 'Electrónica cristiana',
        'House' => 'Electrónica cristiana',
        'Tropical house' => 'Electrónica cristiana',
        'Future bass' => 'Electrónica cristiana',
        'Dubstep' => 'Electrónica cristiana',
        'Trance' => 'Electrónica cristiana',
        'Drum and bass' => 'Electrónica cristiana',
        'Lo-fi' => 'Lo-fi cristiano',
        'Balada' => 'Balada cristiana',
        'Balada romántica' => 'Balada cristiana',
        'Bolero' => 'Bolero cristiano',
        'Salsa' => 'Salsa cristiana',
        'Salsa romántica' => 'Salsa cristiana',
        'Cumbia' => 'Cumbia cristiana',
        'Cumbia peruana' => 'Cumbia cristiana',
        'Tecnocumbia' => 'Cumbia cristiana',
        'Bachata' => 'Bachata cristiana',
        'Bachata urbana' => 'Bachata cristiana',
        'Merengue' => 'Merengue cristiano',
        'Vallenato' => 'Vallenato cristiano',
        'Tropical' => 'Tropical cristiana',
        'Regional mexicano' => 'Regional mexicano cristiano',
        'Ranchera' => 'Ranchera cristiana',
        'Banda' => 'Banda cristiana',
        'Norteño' => 'Norteño cristiano',
        'Mariachi' => 'Mariachi cristiano',
        'Grupera' => 'Grupera cristiana',
        'Corridos' => 'Corridos cristianos',
        'Corridos tumbados' => 'Corridos cristianos',
        'Huayno' => 'Huayno cristiano',
        'Música andina' => 'Música andina cristiana',
        'Folclore latinoamericano' => 'Folclore cristiano',
        'Sertanejo' => 'Gospel brasileño',
        'MPB' => 'Gospel brasileño',
        'Samba' => 'Gospel brasileño',
        'Pagode' => 'Gospel brasileño',
        'Forró' => 'Gospel brasileño',
        'Folk' => 'Folk cristiano',
        'Americana' => 'Folk cristiano',
        'Indie folk' => 'Indie folk cristiano',
        'Country' => 'Country cristiano',
        'Country pop' => 'Country pop cristiano',
        'Bluegrass' => 'Southern gospel',
        'R&B' => 'R&B cristiano',
        'R&B contemporáneo' => 'R&B cristiano',
        'Soul' => 'Soul cristiano',
        'Neo soul' => 'Soul cristiano',
        'Jazz' => 'Jazz cristiano',
        'Smooth jazz' => 'Jazz cristiano',
        'Reggae' => 'Reggae cristiano',
        'Reggae en español' => 'Reggae cristiano',
        'Dancehall' => 'Dancehall cristiano',
        'Ska' => 'Ska cristiano',
        'Afrobeats' => 'Afrogospel',
        'Afrobeat' => 'Afrogospel',
        'Instrumental' => 'Instrumental cristiano',
        'Piano' => 'Instrumental cristiano',
        'Música infantil' => 'Música cristiana infantil',
        'Música navideña' => 'Navidad cristiana',
    ];

    /**
     * Every genre, by family: [name, [other names it goes by]].
     *
     * @return array<string, list<array{0: string, 1: list<string>}>>
     */
    public static function all(): array
    {
        return [
            'cristiana' => [
                ['Música cristiana', ['christian', 'christian music', 'christian & gospel', 'religious', 'religiosa', 'cristiana', 'cristiano', 'musica cristiana', 'inspirational', 'gospel & religious', 'latin christian', 'christian latin']],
                ['Adoración', ['worship', 'worship music', 'christian worship', 'contemporary worship music', 'contemporary worship', 'praise & worship', 'praise and worship', 'alabanza y adoracion', 'adoracion', 'latin worship']],
                ['Alabanza', ['praise', 'praise music', 'alabanza', 'alabanzas', 'jubilo']],
                ['Cristiana contemporánea (CCM)', ['contemporary christian', 'contemporary christian music', 'ccm', 'christian contemporary', 'adult contemporary christian']],
                ['Pop cristiano', ['christian pop', 'pop cristiano', 'gospel pop']],
                ['Pop rock cristiano', ['christian pop rock', 'christian pop/rock']],
                ['Synth-pop cristiano', ['christian synthpop', 'christian synth-pop', 'christian synth pop']],
                ['K-pop cristiano', ['christian k-pop', 'christian kpop', 'korean ccm', 'ccm coreano']],
                ['Acústico cristiano', ['christian acoustic', 'acoustic worship', 'acustico cristiano', 'adoracion acustica', 'worship acustico']],
                ['Rock cristiano', ['christian rock', 'rock cristiano', 'jesus rock']],
                ['Rock alternativo cristiano', ['christian alternative rock', 'christian alternative', 'christian alt rock']],
                ['Indie cristiano', ['christian indie', 'christian indie rock', 'christian indie pop']],
                ['Metal cristiano', ['christian metal', 'white metal', 'christian heavy metal']],
                ['Nu metal cristiano', ['christian nu metal', 'christian nu-metal']],
                ['Metalcore cristiano', ['christian metalcore', 'metalcore cristiano']],
                ['Post-hardcore cristiano', ['christian post-hardcore', 'christian post hardcore']],
                ['Deathcore cristiano', ['christian deathcore']],
                ['Death metal cristiano', ['christian death metal']],
                ['Unblack metal', ['unblack metal', 'christian black metal', 'holy unblack metal']],
                ['Power metal cristiano', ['christian power metal']],
                ['Metal sinfónico cristiano', ['christian symphonic metal']],
                ['Thrash metal cristiano', ['christian thrash metal', 'christian thrash']],
                ['Punk cristiano', ['christian punk']],
                ['Pop punk cristiano', ['christian pop punk', 'christian pop-punk']],
                ['Hardcore cristiano', ['christian hardcore']],
                ['Ska cristiano', ['christian ska', 'ska cristiano']],
                ['Rap cristiano', ['christian hip hop', 'christian rap', 'holy hip hop', 'gospel rap', 'gospel hip hop', 'rap cristiano', 'hip hop cristiano', 'christian hip-hop']],
                ['Drill cristiano', ['christian drill', 'drill cristiano', 'gospel drill']],
                ['Reguetón cristiano', ['christian reggaeton', 'reggaeton cristiano', 'regueton cristiano', 'christian reggaetón']],
                ['Trap cristiano', ['christian trap', 'trap cristiano']],
                ['Urbano cristiano', ['christian urban', 'urbano cristiano', 'musica urbana cristiana', 'christian latin urban']],
                ['Pop urbano cristiano', ['christian urban pop', 'pop urbano cristiano']],
                ['R&B cristiano', ['christian r&b', 'christian rnb', 'gospel r&b', 'r&b cristiano']],
                ['Soul cristiano', ['christian soul', 'gospel soul', 'soul cristiano']],
                ['Jazz cristiano', ['christian jazz', 'gospel jazz', 'jazz cristiano']],
                ['Reggae cristiano', ['christian reggae', 'gospel reggae', 'reggae cristiano']],
                ['Dancehall cristiano', ['christian dancehall', 'gospel dancehall', 'dancehall cristiano']],
                ['Electrónica cristiana', ['christian electronic', 'christian edm', 'christian dance', 'christian electronic dance music']],
                ['Lo-fi cristiano', ['christian lofi', 'christian lo-fi', 'lofi cristiano', 'lofi worship']],
                ['Afrogospel', ['afro gospel', 'african gospel', 'afrogospel', 'afrobeats gospel', 'christian afrobeats']],
                ['Gospel', ['gospel', 'gospel music', 'gospel latino']],
                ['Gospel contemporáneo', ['contemporary gospel', 'urban contemporary gospel', 'modern gospel', 'urban gospel']],
                ['Gospel tradicional', ['traditional gospel', 'black gospel', 'gospel blues']],
                ['Southern gospel', ['southern gospel', 'country gospel', 'bluegrass gospel']],
                ['Coro góspel', ['gospel choir', 'mass choir', 'choir gospel']],
                ['Gospel brasileño', ['brazilian gospel', 'gospel brasileiro', 'musica gospel brasileira', 'louvor', 'adoracao', 'louvor e adoracao']],
                ['Himnos', ['hymns', 'hymn', 'himno', 'himnos', 'himnario', 'hymnal', 'traditional hymns']],
                ['Coros cristianos', ['coritos', 'coros', 'coros cristianos', 'choruses', 'christian choruses']],
                ['Música cristiana infantil', ["christian children's music", 'christian kids', 'children christian', 'infantil cristiana', 'musica cristiana para ninos']],
                ['Navidad cristiana', ['christian christmas', 'christmas worship', 'navidad cristiana', 'villancicos cristianos']],
                ['Balada cristiana', ['christian ballad', 'balada cristiana']],
                ['Bolero cristiano', ['christian bolero', 'bolero cristiano']],
                ['Salsa cristiana', ['christian salsa', 'salsa cristiana']],
                ['Cumbia cristiana', ['christian cumbia', 'cumbia cristiana']],
                ['Bachata cristiana', ['christian bachata', 'bachata cristiana']],
                ['Merengue cristiano', ['christian merengue', 'merengue cristiano']],
                ['Vallenato cristiano', ['christian vallenato', 'vallenato cristiano']],
                ['Tropical cristiana', ['christian tropical', 'tropical cristiana', 'musica tropical cristiana']],
                ['Regional mexicano cristiano', ['christian regional mexican', 'regional mexicano cristiano']],
                ['Ranchera cristiana', ['christian ranchera', 'ranchera cristiana']],
                ['Banda cristiana', ['christian banda', 'banda cristiana']],
                ['Norteño cristiano', ['christian norteno', 'norteno cristiano']],
                ['Mariachi cristiano', ['christian mariachi', 'mariachi cristiano']],
                ['Grupera cristiana', ['christian grupera', 'grupera cristiana']],
                ['Corridos cristianos', ['christian corridos', 'corridos cristianos', 'corrido cristiano']],
                ['Huayno cristiano', ['christian huayno', 'huayno cristiano']],
                ['Música andina cristiana', ['christian andean', 'andina cristiana', 'musica andina cristiana']],
                ['Folclore cristiano', ['christian folklore', 'folclore cristiano', 'folklore cristiano']],
                ['Folk cristiano', ['christian folk', 'folk cristiano']],
                ['Indie folk cristiano', ['christian indie folk']],
                ['Country cristiano', ['christian country', 'country cristiano', 'positive country']],
                ['Country pop cristiano', ['christian country pop']],
                ['Instrumental cristiano', ['christian instrumental', 'instrumental cristiano', 'instrumental worship']],
                ['Música católica', ['catholic', 'catholic music', 'musica catolica', 'catolica']],
                ['Música litúrgica', ['liturgical', 'liturgical music', 'mass', 'musica liturgica']],
                ['Música sacra', ['sacred music', 'sacred', 'church music', 'musica sacra', 'religious music']],
                ['Canto gregoriano', ['gregorian chant', 'plainchant', 'plainsong', 'canto gregoriano']],
                ['Espirituales negros', ['spiritual', 'spirituals', 'negro spiritual', 'african-american spiritual']],
                ['Jesus music', ['jesus music', 'jesus movement']],
                ['Adoración profética', ['prophetic worship', 'spontaneous worship', 'soaking', 'soaking music', 'adoracion profetica', 'adoracion espontanea']],
                ['Música mesiánica', ['messianic', 'messianic music', 'messianic jewish music', 'musica mesianica']],
            ],
            'pop' => [
                ['Pop', ['pop', 'pop music', 'mainstream pop']],
                ['Pop latino', ['latin pop', 'pop latino', 'pop en espanol', 'spanish pop']],
                ['Pop rock', ['pop rock', 'pop/rock', 'pop-rock']],
                ['Pop rock alternativo', ['alternative pop rock', 'alternative pop/rock', 'pop rock alternativo', 'alt pop rock']],
                ['Pop progresivo', ['progressive pop', 'prog pop', 'pop progresivo']],
                ['Pop alternativo', ['alternative pop', 'alt-pop', 'alt pop', 'pop alternativo']],
                ['Indie pop', ['indie pop', 'indie-pop']],
                ['Bedroom pop', ['bedroom pop']],
                ['Indietrónica', ['indietronica', 'indie electronic', 'indie electronica']],
                ['Synth-pop', ['synth-pop', 'synthpop', 'synth pop']],
                ['Electropop', ['electropop', 'electro pop', 'electro-pop']],
                ['Hyperpop', ['hyperpop', 'hyper pop']],
                ['Dance pop', ['dance-pop', 'dance pop']],
                ['Teen pop', ['teen pop']],
                ['Bubblegum pop', ['bubblegum pop', 'bubblegum']],
                ['Pop acústico', ['acoustic pop', 'acoustic', 'acustico', 'pop acustico']],
                ['Pop melódico', ['melodic pop', 'pop melodico']],
                ['Pop soul', ['pop soul', 'blue-eyed soul']],
                ['Power pop', ['power pop']],
                ['Jangle pop', ['jangle pop']],
                ['Twee pop', ['twee pop', 'twee']],
                ['Dream pop', ['dream pop']],
                ['Art pop', ['art pop']],
                ['Pop experimental', ['experimental pop']],
                ['Pop psicodélico', ['psychedelic pop']],
                ['Sunshine pop', ['sunshine pop']],
                ['Pop barroco', ['baroque pop', 'chamber pop']],
                ['Pop orquestal', ['orchestral pop']],
                ['Pop adulto contemporáneo', ['adult contemporary', 'soft pop', 'adult pop']],
                ['Pop tropical', ['tropical pop']],
                ['Europop', ['europop', 'euro pop']],
                ['Pop italiano', ['italian pop', 'musica leggera', 'canzone', 'canzone italiana']],
                ['Yé-yé', ['ye-ye', 'yeye']],
                ['City pop', ['city pop']],
                ['K-pop', ['k-pop', 'kpop', 'korean pop', 'pop coreano']],
                ['J-pop', ['j-pop', 'jpop', 'japanese pop']],
                ['C-pop', ['c-pop', 'cpop', 'mandopop', 'cantopop']],
                ['Balada', ['ballad', 'balada', 'power ballad', 'pop ballad', 'latin ballad']],
                ['Balada romántica', ['romantic ballad', 'balada romantica', 'baladas romanticas', 'romantic']],
            ],
            'rock' => [
                ['Rock', ['rock', 'rock music']],
                ['Rock alternativo', ['alternative rock', 'alternative', 'alt-rock', 'alt rock', 'rock alternativo', 'modern rock']],
                ['Rock en español', ['rock en espanol', 'spanish rock', 'rock latino', 'latin rock']],
                ['Rock argentino', ['rock argentino', 'rock nacional', 'argentine rock']],
                ['Rock mexicano', ['rock mexicano', 'mexican rock']],
                ['Rock peruano', ['rock peruano', 'peruvian rock']],
                ['Rock urbano', ['rock urbano']],
                ['Rock progresivo', ['progressive rock', 'prog rock', 'prog', 'rock progresivo']],
                ['Art rock', ['art rock']],
                ['Indie rock', ['indie rock', 'indie']],
                ['Hard rock', ['hard rock']],
                ['Soft rock', ['soft rock']],
                ['Rock melódico', ['melodic rock', 'aor', 'album oriented rock']],
                ['Yacht rock', ['yacht rock']],
                ['Rock acústico', ['acoustic rock']],
                ['Rock clásico', ['classic rock', 'rock clasico']],
                ['Rock and roll', ['rock and roll', 'rock & roll', "rock 'n' roll", 'rock n roll']],
                ['Rockabilly', ['rockabilly']],
                ['Psychobilly', ['psychobilly']],
                ['Surf rock', ['surf rock', 'surf']],
                ['Garage rock', ['garage rock']],
                ['Glam rock', ['glam rock', 'glam']],
                ['Rock psicodélico', ['psychedelic rock', 'psychedelic', 'psicodelico']],
                ['Neo-psicodelia', ['neo-psychedelia', 'neo psychedelia', 'neopsychedelia']],
                ['Space rock', ['space rock']],
                ['Krautrock', ['krautrock']],
                ['Rock sinfónico', ['symphonic rock']],
                ['Rock instrumental', ['instrumental rock']],
                ['Rock experimental', ['experimental rock']],
                ['Folk rock', ['folk rock', 'folk-rock']],
                ['Heartland rock', ['heartland rock']],
                ['Arena rock', ['arena rock', 'stadium rock']],
                ['Funk rock', ['funk rock']],
                ['Blues rock', ['blues rock', 'blues-rock']],
                ['Southern rock', ['southern rock']],
                ['Stoner rock', ['stoner rock', 'desert rock']],
                ['Rap rock', ['rap rock', 'rapcore']],
                ['Rock electrónico', ['electronic rock', 'electro rock']],
                ['Rock industrial', ['industrial rock']],
                ['New wave', ['new wave']],
                ['Post-punk', ['post-punk', 'post punk']],
                ['Rock gótico', ['gothic rock', 'goth rock', 'goth']],
                ['Darkwave', ['darkwave', 'dark wave', 'coldwave']],
                ['Post-rock', ['post-rock', 'post rock']],
                ['Math rock', ['math rock']],
                ['Noise rock', ['noise rock']],
                ['Slowcore', ['slowcore', 'sadcore']],
                ['Shoegaze', ['shoegaze', 'shoegazing']],
                ['Grunge', ['grunge']],
                ['Post-grunge', ['post-grunge', 'post grunge']],
                ['Emo', ['emo', 'emo pop']],
                ['Midwest emo', ['midwest emo']],
                ['Britpop', ['britpop', 'brit pop']],
            ],
            'metal' => [
                ['Heavy metal', ['heavy metal', 'metal']],
                ['NWOBHM', ['nwobhm', 'new wave of british heavy metal']],
                ['Metal alternativo', ['alternative metal', 'alt metal']],
                ['Nu metal', ['nu metal', 'nu-metal']],
                ['Rap metal', ['rap metal']],
                ['Funk metal', ['funk metal']],
                ['Metal industrial', ['industrial metal']],
                ['Metalcore', ['metalcore']],
                ['Metalcore melódico', ['melodic metalcore']],
                ['Deathcore', ['deathcore']],
                ['Mathcore', ['mathcore']],
                ['Easycore', ['easycore']],
                ['Electronicore', ['electronicore', 'trancecore']],
                ['Metal sinfónico', ['symphonic metal']],
                ['Metal neoclásico', ['neoclassical metal']],
                ['Metal progresivo', ['progressive metal', 'prog metal']],
                ['Djent', ['djent']],
                ['Metal melódico', ['melodic metal']],
                ['Power metal', ['power metal']],
                ['Speed metal', ['speed metal']],
                ['Thrash metal', ['thrash metal', 'thrash']],
                ['Crossover thrash', ['crossover thrash']],
                ['Groove metal', ['groove metal']],
                ['Glam metal', ['glam metal', 'hair metal']],
                ['Death metal', ['death metal']],
                ['Death metal melódico', ['melodic death metal', 'melodeath']],
                ['Death metal técnico', ['technical death metal', 'tech death']],
                ['Black metal', ['black metal']],
                ['Doom metal', ['doom metal', 'doom']],
                ['Sludge metal', ['sludge metal', 'sludge']],
                ['Stoner metal', ['stoner metal']],
                ['Post-metal', ['post-metal', 'post metal']],
                ['Grindcore', ['grindcore', 'grind']],
                ['Metal gótico', ['gothic metal']],
                ['Folk metal', ['folk metal']],
                ['Viking metal', ['viking metal']],
                ['Punk rock', ['punk rock', 'punk']],
                ['Pop punk', ['pop punk', 'pop-punk']],
                ['Punk melódico', ['melodic punk']],
                ['Skate punk', ['skate punk']],
                ['Street punk', ['street punk']],
                ['Anarcopunk', ['anarcho-punk', 'anarcho punk']],
                ['Horror punk', ['horror punk']],
                ['Garage punk', ['garage punk']],
                ['Punk celta', ['celtic punk']],
                ['Folk punk', ['folk punk']],
                ['Hardcore punk', ['hardcore punk', 'hardcore']],
                ['Hardcore melódico', ['melodic hardcore']],
                ['Post-hardcore', ['post-hardcore', 'post hardcore']],
                ['Ska punk', ['ska punk', 'ska-punk']],
                ['Screamo', ['screamo']],
            ],
            'urbano' => [
                ['Reguetón', ['reggaeton', 'reggaetón', 'regueton', 'reguetón', 'reggaeton romantico', 'perreo']],
                ['Reguetón old school', ['old school reggaeton', 'reggaeton old school', 'reggaeton clasico']],
                ['Neoperreo', ['neoperreo']],
                ['Urbano latino', ['latin urban', 'urbano latino', 'musica urbana', 'urbano', 'latin urbano', 'urban latin']],
                ['Pop urbano', ['urban pop', 'pop urbano']],
                ['Trap latino', ['latin trap', 'trap latino', 'trap en espanol']],
                ['Trap', ['trap', 'trap music', 'trap rap']],
                ['Trap soul', ['trap soul', 'trapsoul']],
                ['Plugg', ['plugg', 'pluggnb']],
                ['Phonk', ['phonk', 'drift phonk']],
                ['Hip hop', ['hip hop', 'hip-hop', 'hiphop', 'hip hop music']],
                ['Rap', ['rap', 'rap music']],
                ['Hip hop latino', ['latin hip hop', 'latin rap', 'rap latino', 'hip hop latino', 'latin hip-hop']],
                ['Rap en español', ['spanish hip hop', 'rap en espanol', 'rap espanol', 'spanish rap', 'hip hop en espanol']],
                ['Rap consciente', ['conscious hip hop', 'conscious rap', 'rap consciente']],
                ['Hip hop alternativo', ['alternative hip hop', 'alternative rap']],
                ['Hip hop experimental', ['experimental hip hop']],
                ['Hip hop instrumental', ['instrumental hip hop']],
                ['Rap old school', ['old school hip hop', 'old school rap', 'old-school hip hop']],
                ['Boom bap', ['boom bap', 'boom-bap']],
                ['East Coast hip hop', ['east coast hip hop']],
                ['West Coast hip hop', ['west coast hip hop', 'g-funk']],
                ['Southern hip hop', ['southern hip hop', 'dirty south']],
                ['Gangsta rap', ['gangsta rap', 'gangsta']],
                ['Rap hardcore', ['hardcore hip hop', 'hardcore rap']],
                ['Crunk', ['crunk']],
                ['Pop rap', ['pop rap']],
                ['Rap melódico', ['melodic rap']],
                ['Emo rap', ['emo rap', 'sad rap']],
                ['Cloud rap', ['cloud rap']],
                ['Jazz rap', ['jazz rap', 'jazz hop']],
                ['Rap freestyle', ['freestyle rap', 'batalla de gallos']],
                ['Drill', ['drill', 'uk drill']],
                ['Grime', ['grime']],
                ['Dembow', ['dembow', 'dembow dominicano']],
                ['Mambo dominicano', ['mambo dominicano']],
                ['Reparto', ['reparto']],
                ['Cubatón', ['cubaton']],
                ['Funk carioca', ['funk carioca', 'baile funk', 'funk brasileiro', 'brazilian funk']],
                ['Moombahton', ['moombahton']],
                ['Dancehall', ['dancehall']],
                ['Afrobeats', ['afrobeats', 'afropop', 'afro pop', 'afro-pop']],
                ['Afroswing', ['afroswing']],
                ['R&B contemporáneo', ['contemporary r&b', 'contemporary rnb', 'urban contemporary', 'alternative r&b']],
                ['R&B latino', ['latin r&b', 'r&b latino']],
            ],
            'electronica' => [
                ['Electrónica', ['electronic', 'electronica', 'electronic music', 'electronica music']],
                ['EDM', ['edm', 'electronic dance music', 'dance', 'dance music', 'club']],
                ['House', ['house', 'house music']],
                ['Deep house', ['deep house']],
                ['Tropical house', ['tropical house']],
                ['Progressive house', ['progressive house']],
                ['Electro house', ['electro house']],
                ['Big room', ['big room', 'big room house']],
                ['Future house', ['future house']],
                ['Bass house', ['bass house']],
                ['Tech house', ['tech house']],
                ['Slap house', ['slap house', 'brazilian bass']],
                ['French house', ['french house', 'filter house', 'disco house']],
                ['Chicago house', ['chicago house']],
                ['Acid house', ['acid house']],
                ['Afro house', ['afro house']],
                ['Amapiano', ['amapiano']],
                ['Latin house', ['latin house']],
                ['Techno', ['techno']],
                ['Minimal techno', ['minimal techno', 'minimal']],
                ['Melodic techno', ['melodic techno']],
                ['Hard techno', ['hard techno']],
                ['Trance', ['trance', 'progressive trance', 'uplifting trance']],
                ['Psytrance', ['psytrance', 'psychedelic trance', 'goa trance', 'goa']],
                ['Hardstyle', ['hardstyle']],
                ['Hardcore techno', ['hardcore techno', 'gabber', 'happy hardcore']],
                ['Eurodance', ['eurodance', 'euro dance']],
                ['Italo disco', ['italo disco', 'italo-disco']],
                ['Hi-NRG', ['hi-nrg', 'hi nrg']],
                ['Nu-disco', ['nu-disco', 'nu disco']],
                ['Electro', ['electro', 'electro funk']],
                ['Electroclash', ['electroclash']],
                ['Electro swing', ['electro swing']],
                ['Latin freestyle', ['latin freestyle', 'freestyle music']],
                ['Dubstep', ['dubstep']],
                ['Brostep', ['brostep']],
                ['Dubstep melódico', ['melodic dubstep']],
                ['Chillstep', ['chillstep']],
                ['Trap EDM', ['edm trap', 'festival trap', 'trap edm']],
                ['Drum and bass', ['drum and bass', 'drum & bass', 'drum n bass', 'dnb']],
                ['Liquid drum and bass', ['liquid drum and bass', 'liquid dnb', 'liquid funk']],
                ['Neurofunk', ['neurofunk']],
                ['Jungle', ['jungle']],
                ['Breakbeat', ['breakbeat', 'breaks', 'big beat']],
                ['UK garage', ['uk garage', 'ukg', '2-step', '2-step garage']],
                ['Future garage', ['future garage']],
                ['Footwork', ['footwork', 'juke']],
                ['Jersey club', ['jersey club']],
                ['Future bass', ['future bass']],
                ['Glitch hop', ['glitch hop']],
                ['Glitch', ['glitch']],
                ['IDM', ['idm', 'intelligent dance music']],
                ['Industrial', ['industrial', 'industrial music', 'ebm', 'electronic body music']],
                ['Synthwave', ['synthwave', 'retrowave', 'outrun']],
                ['Vaporwave', ['vaporwave']],
                ['Chiptune', ['chiptune', '8-bit', '8bit', 'chip music']],
                ['Guaracha', ['guaracha', 'aleteo', 'zapateo']],
                ['Tribal guarachero', ['tribal guarachero', 'tribal mexicano']],
                ['Chillout', ['chillout', 'chill out', 'chill']],
                ['Chillwave', ['chillwave']],
                ['Lo-fi', ['lo-fi', 'lofi', 'lo-fi hip hop', 'lofi hip hop', 'chillhop']],
                ['Downtempo', ['downtempo']],
                ['Trip hop', ['trip hop', 'trip-hop']],
                ['Ambient', ['ambient', 'ambient music', 'dark ambient']],
                ['Drone', ['drone', 'drone music']],
            ],
            'tropical' => [
                ['Tropical', ['tropical', 'tropical latin', 'latin tropical', 'musica tropical']],
                ['Salsa', ['salsa', 'salsa dura']],
                ['Salsa romántica', ['salsa romantica', 'romantic salsa']],
                ['Salsa choque', ['salsa choque']],
                ['Boogaloo', ['boogaloo', 'bugalu', 'latin boogaloo']],
                ['Pachanga', ['pachanga']],
                ['Charanga', ['charanga']],
                ['Merengue', ['merengue']],
                ['Merengue típico', ['merengue tipico', 'perico ripiao']],
                ['Merengue urbano', ['merengue urbano', 'merengue de calle']],
                ['Bachata', ['bachata']],
                ['Bachata tradicional', ['bachata tradicional', 'traditional bachata', 'amargue']],
                ['Bachata urbana', ['urban bachata', 'bachata urbana']],
                ['Cumbia', ['cumbia', 'cumbia colombiana']],
                ['Cumbia peruana', ['cumbia peruana', 'chicha', 'peruvian cumbia', 'cumbia andina']],
                ['Tecnocumbia', ['tecnocumbia', 'technocumbia']],
                ['Cumbia amazónica', ['cumbia amazonica']],
                ['Cumbia argentina', ['cumbia argentina']],
                ['Cumbia villera', ['cumbia villera']],
                ['Cumbia santafesina', ['cumbia santafesina']],
                ['Cumbia mexicana', ['cumbia mexicana']],
                ['Cumbia sonidera', ['cumbia sonidera', 'sonidero']],
                ['Cumbia rebajada', ['cumbia rebajada']],
                ['Cumbia digital', ['cumbia digital', 'digital cumbia', 'electro cumbia', 'cumbia electronica']],
                ['Cuarteto', ['cuarteto', 'cuarteto cordobes']],
                ['Porro', ['porro', 'porro sabanero']],
                ['Vallenato', ['vallenato']],
                ['Vallenato romántico', ['vallenato romantico', 'romantic vallenato']],
                ['Tropipop', ['tropipop']],
                ['Champeta', ['champeta']],
                ['Mapalé', ['mapale']],
                ['Bullerengue', ['bullerengue']],
                ['Currulao', ['currulao']],
                ['Gaita zuliana', ['gaita zuliana']],
                ['Son cubano', ['son cubano', 'son', 'cuban son']],
                ['Son montuno', ['son montuno']],
                ['Changüí', ['changui']],
                ['Guajira', ['guajira']],
                ['Guaracha cubana', ['guaracha cubana']],
                ['Danzón', ['danzon']],
                ['Guaguancó', ['guaguanco']],
                ['Rumba cubana', ['rumba cubana']],
                ['Songo', ['songo']],
                ['Timba', ['timba']],
                ['Mambo', ['mambo']],
                ['Chachachá', ['cha-cha-cha', 'chachacha', 'cha cha cha']],
                ['Plena', ['plena']],
                ['Bomba', ['bomba puertorriquena', 'bomba']],
                ['Música jíbara', ['musica jibara', 'jibaro']],
                ['Punta', ['punta', 'punta rock']],
                ['Lambada', ['lambada']],
                ['Kompa', ['kompa', 'compas', 'konpa']],
                ['Zouk', ['zouk']],
                ['Kizomba', ['kizomba']],
                ['Bouyon', ['bouyon']],
                ['Soca', ['soca']],
                ['Calypso', ['calypso']],
                ['Mento', ['mento']],
                ['Steelpan', ['steelpan', 'steel band', 'steel drum']],
            ],
            'regional' => [
                ['Regional mexicano', ['regional mexican', 'regional mexicano', 'musica mexicana', 'mexican', 'musica regional mexicana']],
                ['Regional urbano', ['urban regional mexican', 'musica mexicana urbana']],
                ['Ranchera', ['ranchera', 'rancheras', 'cancion ranchera']],
                ['Bolero ranchero', ['bolero ranchero']],
                ['Mariachi', ['mariachi']],
                ['Son jalisciense', ['son jalisciense']],
                ['Banda', ['banda', 'banda sinaloense', 'banda music']],
                ['Tamborazo', ['tamborazo']],
                ['Norteño', ['norteno', 'norteño', 'nortena', 'musica nortena']],
                ['Norteño-banda', ['nortenobanda', 'norteno banda']],
                ['Cumbia norteña', ['cumbia nortena']],
                ['Corridos', ['corrido', 'corridos']],
                ['Corridos tumbados', ['corridos tumbados', 'corrido tumbado']],
                ['Corridos bélicos', ['corridos belicos', 'corrido belico']],
                ['Corridos alterados', ['corridos alterados', 'movimiento alterado']],
                ['Narcocorrido', ['narcocorrido', 'narcocorridos']],
                ['Sierreño', ['sierreno', 'sierreño']],
                ['Grupera', ['grupero', 'grupera', 'onda grupera']],
                ['Duranguense', ['duranguense']],
                ['Música calentana', ['musica calentana', 'tierra caliente']],
                ['Chilena', ['chilena guerrerense']],
                ['Tejano', ['tejano', 'tex-mex', 'texmex']],
                ['Conjunto tejano', ['conjunto tejano', 'conjunto']],
                ['Huapango', ['huapango', 'son huasteco']],
                ['Son jarocho', ['son jarocho']],
                ['Trova yucateca', ['trova yucateca']],
            ],
            'latina' => [
                ['Folclore latinoamericano', ['latin american folk', 'folklore', 'folclore', 'latin folk', 'musica folclorica']],
                ['Música andina', ['andean', 'andean music', 'musica andina', 'andina']],
                ['Huayno', ['huayno', 'huaino', 'wayno']],
                ['Huaylas', ['huaylas', 'huaylarsh']],
                ['Santiago huanca', ['santiago huanca', 'santiago wanka']],
                ['Carnaval andino', ['carnaval andino']],
                ['Muliza', ['muliza']],
                ['Yaraví', ['yaravi']],
                ['Pasacalle', ['pasacalle']],
                ['Música amazónica', ['musica amazonica', 'amazonian music']],
                ['Música criolla', ['musica criolla', 'criolla', 'peruvian creole music']],
                ['Vals peruano', ['peruvian waltz', 'vals peruano', 'vals criollo']],
                ['Polka criolla', ['polka criolla']],
                ['Marinera', ['marinera']],
                ['Tondero', ['tondero']],
                ['Música afroperuana', ['afro-peruvian', 'afroperuana']],
                ['Festejo', ['festejo']],
                ['Landó', ['lando']],
                ['Zamacueca', ['zamacueca']],
                ['Pasillo', ['pasillo']],
                ['Sanjuanito', ['sanjuanito']],
                ['Albazo', ['albazo']],
                ['Bomba del Chota', ['bomba del chota']],
                ['Rocolera', ['rocolera', 'musica rocolera']],
                ['Caporales', ['caporales']],
                ['Morenada', ['morenada']],
                ['Diablada', ['diablada']],
                ['Saya', ['saya', 'saya afroboliviana']],
                ['Tinku', ['tinku']],
                ['Kullawada', ['kullawada']],
                ['Taquirari', ['taquirari']],
                ['Folclore argentino', ['argentine folk', 'folclore argentino', 'folklore argentino']],
                ['Chacarera', ['chacarera']],
                ['Zamba', ['zamba']],
                ['Chamamé', ['chamame']],
                ['Carnavalito', ['carnavalito']],
                ['Vidala', ['vidala']],
                ['Malambo', ['malambo']],
                ['Tonada', ['tonada']],
                ['Cueca', ['cueca']],
                ['Nueva canción', ['nueva cancion', 'nueva cancion chilena']],
                ['Canción protesta', ['protest song', 'cancion protesta']],
                ['Tango', ['tango']],
                ['Tango electrónico', ['electrotango', 'tango electronico', 'neotango']],
                ['Milonga', ['milonga']],
                ['Candombe', ['candombe']],
                ['Murga', ['murga']],
                ['Bambuco', ['bambuco']],
                ['Sanjuanero', ['sanjuanero']],
                ['Carranga', ['carranga', 'musica carranguera']],
                ['Música popular colombiana', ['musica popular colombiana', 'popular colombiana', 'despecho']],
                ['Música afrocolombiana', ['afro-colombian', 'musica afrocolombiana', 'pacifico colombiano']],
                ['Joropo', ['joropo']],
                ['Música llanera', ['musica llanera', 'llanera']],
                ['Marimba', ['marimba', 'musica de marimba']],
                ['Palo de mayo', ['palo de mayo']],
                ['Bolero', ['bolero', 'boleros']],
                ['Filin', ['filin']],
                ['Nueva trova', ['nueva trova', 'trova', 'trova cubana']],
                ['Música afrocubana', ['afro-cuban', 'musica afrocubana']],
                ['Cantautor', ['singer-songwriter', 'singer/songwriter', 'cantautor', 'cancion de autor']],
                ['Fusión latina', ['latin fusion', 'fusion latina']],
                ['Samba', ['samba']],
                ['Pagode', ['pagode']],
                ['Samba-enredo', ['samba-enredo', 'samba enredo']],
                ['Samba-reggae', ['samba-reggae']],
                ['Bossa nova', ['bossa nova']],
                ['MPB', ['mpb', 'musica popular brasileira', 'brazilian popular music']],
                ['Tropicália', ['tropicalia']],
                ['Choro', ['choro', 'chorinho']],
                ['Forró', ['forro', 'forró']],
                ['Baião', ['baiao']],
                ['Xote', ['xote']],
                ['Frevo', ['frevo']],
                ['Maracatu', ['maracatu']],
                ['Axé', ['axe', 'axé']],
                ['Arrocha', ['arrocha']],
                ['Piseiro', ['piseiro', 'pisadinha']],
                ['Brega', ['brega', 'tecnobrega']],
                ['Sertanejo', ['sertanejo', 'sertanejo universitario']],
                ['Música gaúcha', ['musica gaucha', 'nativista']],
                ['Copla', ['copla', 'cancion espanola']],
                ['Sevillanas', ['sevillanas']],
                ['Pasodoble', ['pasodoble']],
                ['Jota', ['jota']],
            ],
            'jazz' => [
                ['Jazz', ['jazz']],
                ['Dixieland', ['dixieland', 'new orleans jazz', 'trad jazz']],
                ['Ragtime', ['ragtime']],
                ['Swing', ['swing']],
                ['Big band', ['big band']],
                ['Jazz gitano', ['gypsy jazz', 'jazz manouche']],
                ['Bebop', ['bebop', 'bop']],
                ['Hard bop', ['hard bop']],
                ['Cool jazz', ['cool jazz', 'west coast jazz']],
                ['Jazz modal', ['modal jazz']],
                ['Post-bop', ['post-bop', 'post bop']],
                ['Free jazz', ['free jazz', 'avant-garde jazz']],
                ['Soul jazz', ['soul jazz']],
                ['Jazz vocal', ['vocal jazz']],
                ['Jazz contemporáneo', ['contemporary jazz']],
                ['Smooth jazz', ['smooth jazz']],
                ['Acid jazz', ['acid jazz']],
                ['Nu jazz', ['nu jazz', 'nu-jazz']],
                ['Jazz funk', ['jazz-funk', 'jazz funk']],
                ['Jazz latino', ['latin jazz', 'jazz latino', 'afro-cuban jazz']],
                ['Jazz fusión', ['jazz fusion', 'fusion', 'jazz-rock']],
                ['Blues', ['blues']],
                ['Delta blues', ['delta blues']],
                ['Chicago blues', ['chicago blues']],
                ['Texas blues', ['texas blues']],
                ['Blues eléctrico', ['electric blues']],
                ['Blues acústico', ['acoustic blues', 'country blues']],
                ['Soul blues', ['soul blues']],
                ['Soul', ['soul', 'soul music', 'southern soul']],
                ['Neo soul', ['neo soul', 'neo-soul']],
                ['Northern soul', ['northern soul']],
                ['Philly soul', ['philly soul', 'philadelphia soul']],
                ['Soul psicodélico', ['psychedelic soul']],
                ['R&B', ['r&b', 'rnb', 'rhythm and blues', 'r&b/soul', 'r and b']],
                ['Doo-wop', ['doo-wop', 'doo wop']],
                ['Quiet storm', ['quiet storm']],
                ['New jack swing', ['new jack swing']],
                ['Funk', ['funk']],
                ['P-Funk', ['p-funk']],
                ['Go-go', ['go-go']],
                ['Boogie', ['boogie', 'post-disco']],
                ['Motown', ['motown']],
                ['Disco', ['disco']],
            ],
            'clasica' => [
                ['Clásica', ['classical', 'classical music', 'musica clasica', 'clasica', 'western classical music']],
                ['Música medieval', ['medieval', 'medieval music', 'musica medieval']],
                ['Música renacentista', ['renaissance', 'renaissance music', 'musica renacentista']],
                ['Barroca', ['baroque', 'baroque music', 'musica barroca']],
                ['Clasicismo', ['classical period', 'classical era']],
                ['Romanticismo', ['romantic era', 'romantic classical', 'romanticism']],
                ['Impresionismo', ['impressionism', 'impressionist music']],
                ['Neoclásica', ['neoclassical', 'modern classical', 'contemporary classical', 'neo-classical']],
                ['Minimalismo', ['minimalism', 'minimalist', 'minimal music']],
                ['Música electroacústica', ['electroacoustic', 'musique concrete']],
                ['Ópera', ['opera']],
                ['Opereta', ['operetta', 'opereta']],
                ['Zarzuela', ['zarzuela']],
                ['Musical', ['musical', 'musical theatre', 'musical theater', 'show tunes', 'broadway', 'teatro musical']],
                ['Oratorio', ['oratorio']],
                ['Cantata', ['cantata']],
                ['Lied', ['lied', 'art song']],
                ['Coral', ['choral', 'choir', 'coral', 'choral music']],
                ['Orquestal', ['orchestral', 'orchestra', 'orquesta']],
                ['Sinfónica', ['symphony', 'symphonic', 'symphonic music', 'sinfonica']],
                ['Música de cámara', ['chamber music', 'string quartet']],
                ['Marchas y bandas', ['marching band', 'military music', 'marchas', 'banda de guerra']],
                ['Banda sonora', ['soundtrack', 'film score', 'score', 'film soundtrack', 'banda sonora']],
                ['Música de videojuegos', ['video game music', 'game soundtrack', 'vgm', 'videojuegos']],
                ['Música épica', ['epic music', 'trailer music', 'epic orchestral']],
                ['Instrumental', ['instrumental', 'instrumentals']],
                ['Piano', ['piano', 'solo piano', 'piano solo']],
                ['Guitarra clásica', ['classical guitar', 'guitarra clasica']],
                ['Órgano', ['organ', 'organ music']],
                ['Arpa', ['harp']],
                ['Crossover clásico', ['classical crossover', 'operatic pop', 'popera']],
                ['New age', ['new age', 'new-age']],
                ['Música para meditar', ['meditation', 'relaxation', 'healing', 'relajacion', 'meditacion', 'sleep music', 'study music', 'focus music']],
            ],
            'otros' => [
                ['Folk', ['folk', 'folk music', 'contemporary folk']],
                ['Folk tradicional', ['traditional folk']],
                ['Indie folk', ['indie folk', 'folk pop', 'folk-pop']],
                ['Folk psicodélico', ['psychedelic folk']],
                ['Neofolk', ['neofolk']],
                ['Canciones marineras', ['sea shanty', 'sea shanties', 'shanty']],
                ['Country', ['country', 'country music', 'contemporary country']],
                ['Country pop', ['country pop']],
                ['Country rock', ['country rock']],
                ['Country alternativo', ['alternative country', 'alt-country']],
                ['Outlaw country', ['outlaw country']],
                ['Honky tonk', ['honky tonk', 'honky-tonk']],
                ['Western swing', ['western swing']],
                ['Bluegrass', ['bluegrass']],
                ['Americana', ['americana', 'roots rock']],
                ['Cajún', ['cajun']],
                ['Zydeco', ['zydeco']],
                ['Celta', ['celtic', 'celtic music', 'irish folk']],
                ['Flamenco', ['flamenco', 'nuevo flamenco']],
                ['Flamenco pop', ['flamenco pop', 'pop flamenco']],
                ['Rumba', ['rumba', 'rumba flamenca', 'rumba catalana']],
                ['Fado', ['fado']],
                ['Chanson', ['chanson', 'chanson francaise', 'french chanson']],
                ['Schlager', ['schlager']],
                ['Polka', ['polka']],
                ['Música balcánica', ['balkan', 'balkan music', 'balkan brass']],
                ['Música griega', ['greek music', 'rebetiko', 'laiko']],
                ['Klezmer', ['klezmer']],
                ['Música árabe', ['arabic music', 'arabic', 'musica arabe']],
                ['Raï', ['rai']],
                ['Música turca', ['turkish music', 'turkish']],
                ['Qawwali', ['qawwali']],
                ['Bollywood', ['bollywood', 'filmi']],
                ['Música clásica india', ['indian classical', 'hindustani', 'carnatic']],
                ['Bhangra', ['bhangra']],
                ['Música china', ['chinese music', 'chinese traditional']],
                ['Enka', ['enka']],
                ['Gamelan', ['gamelan']],
                ['Música hawaiana', ['hawaiian', 'hawaiian music']],
                ['Música nativa americana', ['native american', 'native american music']],
                ['Música africana', ['african music', 'african']],
                ['Afrobeat', ['afrobeat']],
                ['Highlife', ['highlife']],
                ['Soukous', ['soukous', 'rumba congolesa', 'congolese rumba']],
                ['Mbalax', ['mbalax']],
                ['Kuduro', ['kuduro']],
                ['Gqom', ['gqom']],
                ['Reggae', ['reggae', 'roots reggae']],
                ['Reggae en español', ['latin reggae', 'reggae en espanol', 'reggae latino']],
                ['Reggae fusión', ['reggae fusion']],
                ['Lovers rock', ['lovers rock']],
                ['Rocksteady', ['rocksteady']],
                ['Ragga', ['ragga', 'raggamuffin']],
                ['Dub', ['dub']],
                ['Ska', ['ska']],
                ['Two-tone', ['2 tone', 'two tone', '2-tone']],
                ['Música del mundo', ['world', 'world music', 'worldbeat', 'musica del mundo']],
                ['Música infantil', ["children's music", 'kids', 'children', 'infantil', 'musica infantil', 'nursery rhymes']],
                ['Canciones de cuna', ['lullaby', 'lullabies', 'canciones de cuna', 'cancion de cuna']],
                ['Música navideña', ['christmas', 'christmas music', 'holiday', 'navidad', 'villancicos', 'villancico', 'christmas carols']],
                ['Himnos nacionales', ['national anthem', 'himno nacional', 'himnos nacionales']],
                ['A capella', ['a cappella', 'acapella', 'a capella']],
                ['Barbershop', ['barbershop', 'barbershop quartet']],
                ['Palabra hablada', ['spoken word', 'poetry', 'sermon', 'predicacion', 'audiobook', 'podcast']],
                ['Comedia', ['comedy', 'stand-up comedy', 'humor']],
                ['Jingles', ['jingle', 'jingles']],
                ['Efectos de sonido', ['sound effects', 'sfx']],
                ['Sonidos de la naturaleza', ['nature sounds', 'sonidos de la naturaleza']],
                ['Easy listening', ['easy listening', 'lounge']],
                ['Exótica', ['exotica']],
                ['Experimental', ['experimental', 'avant-garde']],
                ['Noise', ['noise', 'noise music']],
            ],
        ];
    }
}
