import { usePage } from "@inertiajs/react";
import type { SiteSettings } from "@/lib/types";

type Entry = { readonly key: string; readonly label: string; readonly value: string; readonly area?: boolean; readonly hint?: string };
type Group = { readonly id: string; readonly title: string; readonly note?: string; readonly entries: readonly Entry[] };

export const copyGroups = [
  {
    id: "nav",
    title: "Menú y cabecera",
    note: "Se ven en todas las páginas, arriba y en el menú del celular.",
    entries: [
      { key: "nav.brand", label: "Nombre junto al logo", value: "Iglesia Zoe" },
      { key: "nav.about", label: "Menú · Conócenos", value: "Conócenos" },
      { key: "nav.aboutNote", label: "Menú celular · nota de Conócenos", value: "Historia y pastores" },
      { key: "nav.ministries", label: "Menú · Ministerios", value: "Ministerios" },
      { key: "nav.ministriesNote", label: "Menú celular · nota de Ministerios", value: "Cada generación" },
      { key: "nav.baptism", label: "Menú · Bautismo", value: "Bautismo" },
      { key: "nav.baptismNote", label: "Menú celular · nota de Bautismo", value: "Tu nuevo comienzo" },
      { key: "nav.sermons", label: "Menú · Prédicas", value: "Prédicas" },
      { key: "nav.sermonsNote", label: "Menú celular · nota de Prédicas", value: "Mensajes y series" },
      { key: "nav.prayer", label: "Menú · Oración", value: "Oración" },
      { key: "nav.prayerNote", label: "Menú celular · nota de Oración", value: "Estamos contigo" },
      { key: "nav.give", label: "Menú · Dar", value: "Dar" },
      { key: "nav.giveNote", label: "Menú celular · nota de Dar", value: "Generosidad" },
      { key: "nav.serve", label: "Menú · Involúcrate (grupo)", value: "Involúcrate" },
      { key: "nav.areas", label: "Menú · Áreas de servicio", value: "Áreas de servicio" },
      { key: "nav.areasNote", label: "Menú · nota de Áreas de servicio", value: "Sirve con tus dones" },
      { key: "nav.register", label: "Menú · Regístrate para servir", value: "Regístrate para servir" },
      { key: "nav.registerNote", label: "Menú · nota de Regístrate", value: "Únete a un equipo" },
      { key: "nav.serveDropKicker", label: "Desplegable de Involúcrate · etiqueta", value: "Servir" },
      { key: "nav.serveDropTitle", label: "Desplegable de Involúcrate · título", value: "Hay un lugar para ti" },
      { key: "nav.studies", label: "Menú · Estudios (grupo)", value: "Estudios" },
      { key: "nav.route", label: "Menú · La Ruta del Servidor", value: "La Ruta del Servidor" },
      { key: "nav.routeNote", label: "Menú · nota de La Ruta del Servidor", value: "Cinco niveles para crecer" },
      { key: "nav.studentAccess", label: "Menú · Acceso de estudiantes", value: "Acceso de estudiantes" },
      { key: "nav.studentAccessNote", label: "Menú · nota de Acceso de estudiantes", value: "Notas, horario, lecturas y avisos" },
      { key: "nav.events", label: "Menú · Eventos", value: "Eventos" },
      { key: "nav.eventsNote", label: "Menú · nota de Eventos", value: "Lo que se viene" },
      { key: "nav.resources", label: "Menú · Recursos (grupo)", value: "Recursos" },
      { key: "nav.teachings", label: "Menú · Enseñanzas", value: "Enseñanzas" },
      { key: "nav.teachingsNote", label: "Menú · nota de Enseñanzas", value: "Prédica y grupos" },
      { key: "nav.gallery", label: "Menú · Galería de cultos", value: "Galería de cultos" },
      { key: "nav.galleryNote", label: "Menú · nota de Galería", value: "Fotos de cada servicio" },
      { key: "nav.devotionals", label: "Menú · Devocionales", value: "Devocionales" },
      { key: "nav.devotionalsNote", label: "Menú · nota de Devocionales", value: "Palabra para cada día" },
      { key: "nav.home", label: "Menú celular · enlace al inicio", value: "Inicio" },
      { key: "nav.live", label: "Botón en vivo", value: "En vivo" },
      { key: "nav.access", label: "Enlace al sistema", value: "Acceso al sistema" },
      { key: "nav.dropKicker", label: "Desplegable de ministerios · etiqueta", value: "Crecer" },
      { key: "nav.dropTitle", label: "Desplegable de ministerios · título", value: "Un lugar para cada etapa" },
      { key: "nav.dropAll", label: "Desplegable de ministerios · enlace", value: "Ver todos →" },
      { key: "nav.menuKicker", label: "Menú celular · etiqueta del recuadro", value: "Siguiente paso" },
      { key: "nav.menuTitle", label: "Menú celular · título del recuadro", value: "Te esperamos en casa." },
      { key: "nav.menuText", label: "Menú celular · texto del recuadro", value: "Cuéntanos que vienes y un equipo de bienvenida estará atento.", area: true },
      { key: "nav.fab", label: "Botón flotante de Messenger", value: "Escríbenos" },
    ],
  },
  {
    id: "footer",
    title: "Pie de página",
    entries: [
      { key: "footer.brand", label: "Nombre", value: "iglesia zoe" },
      { key: "footer.colKnow", label: "Columna 1 · título", value: "Conoce" },
      { key: "footer.colNext", label: "Columna 2 · título", value: "Siguiente paso" },
      { key: "footer.colVisit", label: "Columna 3 · título", value: "Visítanos" },
      { key: "footer.give", label: "Enlace a generosidad", value: "Generosidad" },
      { key: "footer.messenger", label: "Enlace a Messenger", value: "Escríbenos por Messenger" },
      { key: "footer.whatsapp", label: "Enlace a WhatsApp", value: "Escríbenos por WhatsApp" },
    ],
  },
  {
    id: "home",
    title: "Inicio",
    note: "Los títulos y textos de cada sección del inicio se editan en Contenido. Aquí van las etiquetas, enlaces y el formulario corto.",
    entries: [
      { key: "home.countdownNext", label: "Cuenta regresiva · texto", value: "Siguiente culto" },
      { key: "home.countdownLive", label: "Cuenta regresiva · en vivo", value: "Estamos reunidos" },
      { key: "home.essenceKicker", label: "Nuestra esencia · etiqueta", value: "Por qué somos Zoe" },
      { key: "home.cellsKicker", label: "La vida en casas · etiqueta", value: "El latido celular" },
      { key: "home.generationsKicker", label: "Redes y ministerios · etiqueta", value: "Redes y ministerios" },
      { key: "home.generationsMore", label: "Redes y ministerios · enlace", value: "Ver todos los ministerios" },
      { key: "home.eventsKicker", label: "Próximos eventos · etiqueta", value: "Próximos eventos" },
      { key: "home.eventsMore", label: "Próximos eventos · enlace", value: "Ver toda la agenda" },
      { key: "home.resourcesKicker", label: "Recursos · etiqueta", value: "Prédicas y recursos" },
      { key: "home.resourcesMore", label: "Recursos · enlace", value: "Ver todas las prédicas" },
      { key: "home.resourcesEmpty", label: "Recursos · si no hay prédicas", value: "Muy pronto publicaremos aquí los mensajes más recientes.", area: true },
      { key: "home.visitKicker", label: "Visita · etiqueta", value: "Planifica tu visita" },
      { key: "facts.sunday", label: "Etiqueta del horario principal", value: "Domingo", hint: "También se usa en Conócenos." },
      { key: "facts.week", label: "Etiqueta del horario entre semana", value: "Entre semana", hint: "También se usa en Conócenos." },
      { key: "facts.place", label: "Etiqueta de la sede", value: "Sede", hint: "También se usa en Conócenos." },
      { key: "home.visitFormTitle", label: "Visita · título del formulario", value: "Avísanos que vienes" },
      { key: "home.visitFormText", label: "Visita · texto del formulario", value: "Déjanos tus datos y un equipo de la casa te recibirá con los brazos abiertos.", area: true },
    ],
  },
  {
    id: "about",
    title: "Conócenos",
    entries: [
      { key: "about.pastorsKicker", label: "Pastores · etiqueta", value: "Pastores" },
      { key: "about.historyKicker", label: "Historia · etiqueta", value: "01 · Casa" },
      { key: "about.historyTitle", label: "Historia · título", value: "Nuestra historia" },
      { key: "about.visionKicker", label: "Visión · etiqueta", value: "Visión" },
      { key: "about.valuesKicker", label: "Valores · etiqueta", value: "02 · Cómo vivimos" },
      { key: "about.firstKicker", label: "Primera vez · etiqueta", value: "Bienvenida" },
      { key: "about.firstTitle", label: "Primera vez · título", value: "¿Vienes por primera vez?" },
      { key: "about.firstText", label: "Primera vez · texto", value: "Si es tu primera vez en la iglesia queremos seguir en contacto contigo.", area: true },
      { key: "about.firstCta", label: "Primera vez · frase del botón", value: "Por favor llena este breve formulario." },
      { key: "about.firstPill", label: "Primera vez · botón", value: "Conoce más aquí" },
    ],
  },
  {
    id: "ministries",
    title: "Ministerios",
    entries: [
      { key: "ministries.kicker", label: "Etiqueta de la página", value: "Ministerios" },
      { key: "ministries.back", label: "Enlace para volver (página de cada ministerio)", value: "Ministerios" },
    ],
  },
  {
    id: "visit",
    title: "Planifica tu visita",
    entries: [
      { key: "visit.kicker", label: "Etiqueta de la página", value: "Primera vez" },
      { key: "visit.formKicker", label: "Formulario · etiqueta", value: "Bienvenida" },
      { key: "visit.formTitle", label: "Formulario · título", value: "Deja tus datos y te recibimos." },
      { key: "visit.formText", label: "Formulario · texto", value: "Un equipo de la casa estará atento para acompañarte en tu primera visita.", area: true },
      { key: "visit.contactKicker", label: "Contacto · etiqueta", value: "Visítanos" },
      { key: "visit.contactTitle", label: "Contacto · título", value: "Nuestros datos de contacto" },
      { key: "visit.phoneTitle", label: "Tarjeta teléfono · título", value: "Nuestros teléfonos" },
      { key: "visit.phoneCall", label: "Tarjeta teléfono · llamar", value: "Llámanos" },
      { key: "visit.phoneWrite", label: "Tarjeta teléfono · escribir", value: "Escríbenos" },
      { key: "visit.messenger", label: "Tarjeta teléfono · Messenger", value: "Messenger de la iglesia" },
      { key: "visit.whatsapp", label: "Tarjeta teléfono · WhatsApp", value: "WhatsApp de la iglesia" },
      { key: "visit.addressTitle", label: "Tarjeta dirección · título", value: "Nuestra dirección" },
      { key: "visit.addressSub", label: "Tarjeta dirección · subtítulo", value: "Visítanos" },
      { key: "visit.mailTitle", label: "Tarjeta correo · título", value: "Nuestro correo" },
      { key: "visit.mailSub", label: "Tarjeta correo · subtítulo", value: "Contáctanos" },
      { key: "visit.mailNote", label: "Tarjeta correo · nota", value: "Te respondemos lo antes posible." },
    ],
  },
  {
    id: "baptism",
    title: "Bautismos",
    entries: [
      { key: "baptism.kicker", label: "Etiqueta de la página", value: "Bautismos" },
      { key: "baptism.formKicker", label: "Formulario · etiqueta", value: "Inscripción" },
      { key: "baptism.formTitle", label: "Formulario · título", value: "Da el paso hoy." },
      { key: "baptism.formText", label: "Formulario · texto", value: "Déjanos tus datos y un servidor de la iglesia te acompañará en todo el proceso.", area: true },
      { key: "baptism.videoKicker", label: "Video · etiqueta", value: "Antes de inscribirte" },
      { key: "baptism.galleryKicker", label: "Galería · etiqueta", value: "Galería" },
      { key: "baptism.galleryTitle", label: "Galería · título", value: "Vidas que dieron el paso" },
      { key: "baptism.galleryCaption", label: "Galería · frase final", value: "Cada bautismo es una historia de fe que comienza de nuevo." },
    ],
  },
  {
    id: "sermons",
    title: "Prédicas",
    entries: [
      { key: "sermons.kicker", label: "Etiqueta de la página", value: "Prédicas" },
      { key: "sermons.overlay", label: "Etiqueta sobre la foto (opción Casa)", value: "Domingo" },
      { key: "sermons.library", label: "Biblioteca · título", value: "Biblioteca" },
      { key: "sermons.libraryEmpty", label: "Biblioteca · texto si está vacía", value: "Los mensajes anteriores aparecerán aquí, organizados por serie.", area: true },
      { key: "sermons.defaultSeries", label: "Nombre para prédicas sin serie", value: "Mensajes" },
    ],
  },
  {
    id: "give",
    title: "Generosidad",
    note: "Los números de cuenta y el QR se editan en la pestaña Generosidad.",
    entries: [
      { key: "give.kicker", label: "Etiqueta de la página", value: "Generosidad" },
      { key: "give.transferTitle", label: "Transferencia · título", value: "Transferencia" },
      { key: "give.bank", label: "Transferencia · banco", value: "Banco BCP" },
      { key: "give.soles", label: "Etiqueta · cuenta soles", value: "Cuenta soles" },
      { key: "give.solesCci", label: "Etiqueta · CCI soles", value: "CCI soles" },
      { key: "give.dollars", label: "Etiqueta · cuenta dólares", value: "Cuenta dólares" },
      { key: "give.dollarsCci", label: "Etiqueta · CCI dólares", value: "CCI dólares" },
      { key: "give.holder", label: "Texto antes del titular", value: "A nombre de" },
      { key: "give.empty", label: "Texto si no hay cuentas", value: "Las cuentas se publican cuando el administrador las registra." },
      { key: "give.yapeTitle", label: "Yape · título", value: "Yape / Plin" },
      { key: "give.qrCaption", label: "Yape · texto bajo el QR", value: "Escanea con Yape o Plin" },
      { key: "give.cardTitle", label: "Tarjeta · título", value: "Con tarjeta" },
      { key: "give.cardButton", label: "Tarjeta · botón", value: "Dar con tarjeta" },
      { key: "give.waysKicker", label: "Formas de dar · etiqueta", value: "Formas de dar" },
      { key: "give.abroadTitle", label: "Extranjero · título", value: "Desde el extranjero" },
      { key: "give.swift", label: "Extranjero · etiqueta SWIFT", value: "Código SWIFT" },
      { key: "give.abroadConfirm", label: "Extranjero · botón", value: "Confirmar mi aporte" },
      { key: "give.abroadMessage", label: "Extranjero · mensaje de WhatsApp", value: "Hola, hice una ofrenda desde el extranjero y quiero confirmarla.", area: true },
      { key: "give.verse", label: "Versículo", value: "Cada uno dé como propuso en su corazón, porque Dios ama al dador alegre. | 2 Corintios 9:7", hint: "Texto | cita." },
    ],
  },
  {
    id: "events",
    title: "Eventos",
    note: "Los eventos se publican en la pestaña Eventos. El título y el texto de la página se editan en Encabezados y Ruta.",
    entries: [
      { key: "events.kicker", label: "Etiqueta de la página", value: "Eventos" },
      { key: "events.next", label: "Etiqueta del evento destacado", value: "Próximo" },
      { key: "events.agenda", label: "Agenda · título", value: "Agenda" },
      { key: "events.when", label: "Etiqueta · cuándo", value: "Cuándo" },
      { key: "events.where", label: "Etiqueta · dónde", value: "Dónde" },
      { key: "events.more", label: "Botón · ver información", value: "Ver información" },
      { key: "events.close", label: "Botón · cerrar", value: "Cerrar" },
      { key: "events.empty", label: "Texto si no hay eventos", value: "Muy pronto anunciaremos aquí los próximos encuentros de la casa.", area: true },
    ],
  },
  {
    id: "teachings",
    title: "Recursos",
    note: "Las enseñanzas se suben en la pestaña Recursos del panel.",
    entries: [
      { key: "teachings.kicker", label: "Etiqueta de la página", value: "Recursos" },
      { key: "teachings.all", label: "Filtro · todo", value: "Todo" },
      { key: "teachings.kindSermon", label: "Filtro · de la prédica", value: "De la prédica" },
      { key: "teachings.kindGroups", label: "Filtro · para los GC", value: "Para los GC" },
      { key: "teachings.search", label: "Buscador", value: "Buscar una enseñanza" },
      { key: "teachings.download", label: "Botón · descargar", value: "Descargar" },
      { key: "teachings.watch", label: "Botón · ver video", value: "Ver video" },
      { key: "teachings.empty", label: "Texto si no hay recursos", value: "Muy pronto publicaremos aquí las enseñanzas para descargar.", area: true },
      { key: "teachings.sermons", label: "Enlace a prédicas", value: "¿Buscas los mensajes en video? Ver prédicas" },
      { key: "teachings.more", label: "Accesos · etiqueta", value: "Más recursos" },
      { key: "teachings.listTitle", label: "Enseñanzas · título", value: "Enseñanzas para descargar" },
    ],
  },
  {
    id: "gallery",
    title: "Galería de cultos",
    note: "Los álbumes y sus fotos se suben en la pestaña Galería de cultos del panel.",
    entries: [
      { key: "gallery.kicker", label: "Etiqueta de la página", value: "Recursos · Galería" },
      { key: "gallery.title", label: "Título", value: "Lo que Dios hace en la casa", hint: "La última palabra se ve en cursiva." },
      { key: "gallery.text", label: "Texto", value: "Revive cada culto dominical y de media semana: la adoración, la Palabra y la familia de Zoe reunida.", area: true },
      { key: "gallery.all", label: "Filtro · todos", value: "Todos" },
      { key: "gallery.sunday", label: "Filtro · domingos", value: "Domingos" },
      { key: "gallery.midweek", label: "Filtro · media semana", value: "Media semana" },
      { key: "gallery.special", label: "Filtro · especiales", value: "Especiales" },
      { key: "gallery.kindSunday", label: "Etiqueta · culto dominical", value: "Culto dominical" },
      { key: "gallery.kindMidweek", label: "Etiqueta · culto de media semana", value: "Media semana" },
      { key: "gallery.kindSpecial", label: "Etiqueta · servicio especial", value: "Servicio especial" },
      { key: "gallery.latest", label: "Etiqueta del álbum más reciente", value: "Último culto" },
      { key: "gallery.photos", label: "Palabra después del número de fotos", value: "fotos" },
      { key: "gallery.open", label: "Botón · ver álbum", value: "Ver fotos" },
      { key: "gallery.back", label: "Álbum · enlace para volver", value: "Galería de cultos" },
      { key: "gallery.download", label: "Visor · descargar", value: "Descargar" },
      { key: "gallery.close", label: "Visor · cerrar", value: "Cerrar" },
      { key: "gallery.others", label: "Álbum · otros cultos", value: "Otros cultos" },
      { key: "gallery.empty", label: "Texto si no hay álbumes", value: "Muy pronto compartiremos aquí las fotos de nuestros cultos.", area: true },
    ],
  },
  {
    id: "devotionals",
    title: "Devocionales",
    note: "Los devocionales se escriben y programan en la pestaña Devocionales del panel.",
    entries: [
      { key: "devotionals.kicker", label: "Etiqueta de la página", value: "Recursos · Devocionales" },
      { key: "devotionals.title", label: "Título", value: "Un tiempo a solas con Dios", hint: "La última palabra se ve en cursiva." },
      { key: "devotionals.text", label: "Texto", value: "Una reflexión breve en la Palabra para empezar tu día, orar y caminar la semana de la mano de Jesús.", area: true },
      { key: "devotionals.latest", label: "Etiqueta del devocional destacado", value: "Devocional de hoy" },
      { key: "devotionals.read", label: "Botón · leer", value: "Leer devocional" },
      { key: "devotionals.minutes", label: "Palabra después de los minutos", value: "min de lectura" },
      { key: "devotionals.search", label: "Buscador", value: "Buscar un devocional" },
      { key: "devotionals.archive", label: "Archivo · título", value: "Devocionales anteriores" },
      { key: "devotionals.back", label: "Devocional · enlace para volver", value: "Devocionales" },
      { key: "devotionals.prayer", label: "Devocional · invitación a orar", value: "¿Quieres que oremos contigo?" },
      { key: "devotionals.prayerCta", label: "Devocional · botón de oración", value: "Envía tu petición" },
      { key: "devotionals.share", label: "Devocional · compartir", value: "Compartir por WhatsApp" },
      { key: "devotionals.copy", label: "Devocional · copiar enlace", value: "Copiar enlace" },
      { key: "devotionals.copied", label: "Devocional · enlace copiado", value: "¡Enlace copiado!" },
      { key: "devotionals.more", label: "Devocional · más devocionales", value: "Sigue leyendo" },
      { key: "devotionals.empty", label: "Texto si no hay devocionales", value: "Muy pronto publicaremos aquí el primer devocional.", area: true },
    ],
  },
  {
    id: "serve",
    title: "Involúcrate",
    note: "Las áreas, sus equipos y sus fotos se editan en la pestaña Involúcrate · áreas. El título y el texto de la página, en Encabezados y Ruta.",
    entries: [
      { key: "serve.kicker", label: "Etiqueta de la página", value: "Involúcrate" },
      { key: "serve.register", label: "Botón · regístrate", value: "Regístrate para servir" },
      { key: "serve.areasCta", label: "Botón · ver áreas", value: "Ver las áreas" },
      { key: "serve.whyKicker", label: "Por qué servir · etiqueta", value: "Servidores" },
      { key: "serve.whyTitle", label: "Por qué servir · título", value: "¿Por qué unirte a un área de servicio?" },
      {
        key: "serve.whyPoints",
        label: "Por qué servir · razones",
        value: "El servicio es parte del ADN de nuestra iglesia.\nServir fortalece tu fe y te conecta con la misión de Dios.\nDescubres y desarrollas tus dones y talentos.\nEncuentras una familia que camina contigo con la misma visión.",
        area: true,
        hint: "Una razón por línea.",
      },
      { key: "serve.quote", label: "Testimonio · frase", value: "Encontré una familia en el equipo de servidores; servir cambió mi vida.", area: true },
      { key: "serve.quoteNote", label: "Testimonio · firma", value: "Una sola iglesia, un solo corazón." },
      { key: "serve.areasKicker", label: "Áreas · etiqueta", value: "Áreas donde puedes servir" },
      { key: "serve.areasTitle", label: "Áreas · título", value: "Elige el equipo que enciende tu corazón" },
      { key: "serve.areaMore", label: "Áreas · enlace a cada página", value: "Conoce el área" },
      { key: "serve.teamsKicker", label: "Equipos · etiqueta", value: "Equipos" },
      { key: "serve.formKicker", label: "Registro · etiqueta", value: "Regístrate" },
      { key: "serve.formTitle", label: "Registro · título", value: "Da el siguiente paso y únete a servir." },
      { key: "serve.formText", label: "Registro · texto", value: "Déjanos tus datos y el equipo del área te escribirá para darte la bienvenida y contarte cómo empezar.", area: true },
      { key: "serve.area", label: "Registro · campo del área", value: "Área donde quieres servir" },
      { key: "serve.team", label: "Registro · campo del equipo", value: "Equipo" },
      { key: "serve.teamAny", label: "Registro · equipo sin elegir", value: "Aún no lo sé" },
      { key: "serve.notes", label: "Registro · campo del mensaje", value: "¿Algo que quieras contarnos?" },
      { key: "serve.notesPlaceholder", label: "Registro · mensaje (texto de ayuda)", value: "Tus dones, tu experiencia o los horarios en que puedes servir." },
      { key: "serve.submit", label: "Registro · botón", value: "Quiero servir" },
      { key: "serve.thanks", label: "Registro · mensaje al enviar", value: "¡Gracias, {nombre}! Recibimos tu registro para {area}. Muy pronto te escribiremos para darte la bienvenida.", area: true, hint: "{nombre} y {area} se reemplazan solos." },
      { key: "serve.again", label: "Registro · botón para registrar a otra persona", value: "Registrar a otra persona" },
      { key: "serve.areaRegister", label: "Página del área · botón", value: "Quiero servir en {area}", hint: "{area} se reemplaza por el nombre del área." },
      { key: "serve.back", label: "Página del área · enlace para volver", value: "Involúcrate" },
      { key: "serve.otherAreas", label: "Página del área · otras áreas", value: "Otras áreas de servicio" },
      { key: "serve.alsoKicker", label: "También en Zoe · etiqueta", value: "También en Zoe" },
      { key: "serve.alsoTitle", label: "También en Zoe · título", value: "Cuidado pastoral y formación" },
      { key: "serve.noSignup", label: "Página sin registro · texto", value: "Escríbenos y el equipo te contará cómo acompañarte o cómo empezar.", area: true },
      { key: "serve.routeTitle", label: "Invitación a la ruta · título", value: "¿Quieres servir en un grupo celular?" },
      { key: "serve.routeCta", label: "Invitación a la ruta · enlace", value: "Conoce la Ruta del servidor" },
      { key: "serve.prev", label: "Carrusel · flecha anterior (lectores de pantalla)", value: "Área anterior" },
      { key: "serve.next", label: "Carrusel · flecha siguiente (lectores de pantalla)", value: "Área siguiente" },
    ],
  },
  {
    id: "route",
    title: "Ruta del servidor",
    note: "Los niveles se editan en la pestaña Encabezados y Ruta; sus fotos, en Imágenes y videos.",
    entries: [
      { key: "route.kicker", label: "Etiqueta de la página", value: "Estudios" },
      { key: "route.levelsKicker", label: "Niveles · etiqueta", value: "Niveles" },
      { key: "route.levelsTitle", label: "Niveles · título", value: "Paso a paso, nivel por nivel." },
      { key: "route.level", label: "Palabra antes del número", value: "Nivel" },
      { key: "route.accessKicker", label: "Aula virtual · etiqueta", value: "Aula virtual" },
      { key: "route.accessTitle", label: "Aula virtual · título", value: "Tu avance, siempre a la mano." },
      { key: "route.accessText", label: "Aula virtual · texto", value: "Cada estudiante tiene su propio acceso para seguir su nivel desde el celular.", area: true },
      { key: "route.accessButton", label: "Aula virtual · botón", value: "Ingresar al aula" },
      { key: "route.accessHelp", label: "Aula virtual · ayuda", value: "Tu usuario es tu DNI. Si aún no tienes clave, pídela a tu maestro." },
      { key: "route.ctaTitle", label: "Invitación · título", value: "¿Listo para dar el primer paso?" },
      { key: "route.ctaText", label: "Invitación · texto", value: "Escríbenos y te contamos cuándo inicia el próximo grupo.", area: true },
      { key: "route.cta", label: "Invitación · botón", value: "Quiero empezar" },
      { key: "route.message", label: "Mensaje de WhatsApp", value: "Hola, quiero empezar la Ruta del servidor." },
    ],
  },
  {
    id: "contact",
    title: "Contacto y oración",
    entries: [
      { key: "contact.kicker", label: "Etiqueta de la página", value: "Oración" },
      { key: "contact.messenger", label: "Enlace a Messenger", value: "Messenger" },
      { key: "contact.whatsapp", label: "Enlace a WhatsApp", value: "WhatsApp" },
      { key: "contact.map", label: "Enlace al mapa", value: "Cómo llegar" },
      { key: "prayer.kicker", label: "Panel de oración · etiqueta", value: "Oramos contigo" },
      { key: "prayer.title", label: "Panel de oración · título", value: "No tienes que *cargarlo solo.*", hint: "Lo que escribas entre asteriscos se ve en cursiva." },
      {
        key: "prayer.verses",
        label: "Panel de oración · versículos",
        value:
          "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios. | Filipenses 4:6\nClama a mí, y yo te responderé, y te enseñaré cosas grandes y ocultas que tú no conoces. | Jeremías 33:3\nPedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá. | Mateo 7:7\nEchando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros. | 1 Pedro 5:7\nCercano está Jehová a todos los que le invocan, a todos los que le invocan de veras. | Salmos 145:18\nOrad unos por otros… La oración eficaz del justo puede mucho. | Santiago 5:16",
        area: true,
        hint: "Un versículo por línea: texto | cita.",
      },
      { key: "prayer.step1Title", label: "Paso 1 · título", value: "Escribe tu petición" },
      { key: "prayer.step1Text", label: "Paso 1 · texto", value: "Cuéntanos el motivo con la confianza de que será tratado con respeto." },
      { key: "prayer.step2Title", label: "Paso 2 · título", value: "Oramos por ti" },
      { key: "prayer.step2Text", label: "Paso 2 · texto", value: "Nuestro equipo de intercesión presenta cada petición delante de Dios durante la semana." },
      { key: "prayer.step3Title", label: "Paso 3 · título", value: "Te acompañamos" },
      { key: "prayer.step3Text", label: "Paso 3 · texto", value: "Si nos dejas tu teléfono, un servidor de la casa puede escribirte." },
      { key: "contact.formKicker", label: "Formulario · etiqueta", value: "Escríbenos" },
      { key: "contact.formText", label: "Formulario · texto", value: "Elige el motivo y cuéntanos tu petición. Oraremos por ti con cariño y discreción.", area: true },
      { key: "prayer.privacy", label: "Formulario · nota de privacidad", value: "Tu petición es confidencial: solo la recibe el equipo pastoral y de intercesión." },
      { key: "prayer.thanks", label: "Mensaje al enviar", value: "Recibimos tu petición. Nuestro equipo de intercesión estará orando por ti esta semana.", area: true },
      { key: "prayer.thanksVerse", label: "Versículo al enviar", value: "«La oración eficaz del justo puede mucho.» Santiago 5:16" },
      { key: "contact.visitKicker", label: "Invitación final · etiqueta", value: "¿Quieres conocernos en persona?" },
      { key: "contact.visitTitle", label: "Invitación final · título", value: "Planifica tu visita" },
      { key: "contact.visitText", label: "Invitación final · texto", value: "Déjanos tus datos y un equipo de la casa te recibirá en tu primera visita.", area: true },
    ],
  },
  {
    id: "forms",
    title: "Formularios",
    note: "Los campos de los formularios de visita, bautismo y oración.",
    entries: [
      { key: "forms.firstName", label: "Campo · nombres", value: "Nombres" },
      { key: "forms.lastName", label: "Campo · apellidos", value: "Apellidos" },
      { key: "forms.sex", label: "Campo · sexo", value: "Sexo" },
      { key: "forms.age", label: "Campo · edad", value: "Edad" },
      { key: "forms.agePlaceholder", label: "Campo · edad (texto de ayuda)", value: "Años" },
      { key: "forms.marital", label: "Campo · estado civil", value: "Estado civil" },
      { key: "forms.country", label: "Campo · país", value: "País" },
      { key: "forms.phone", label: "Campo · teléfono", value: "Teléfono" },
      { key: "forms.phonePlaceholder", label: "Campo · teléfono (texto de ayuda)", value: "Número" },
      { key: "forms.email", label: "Campo · correo", value: "Correo electrónico" },
      { key: "forms.optional", label: "Marca de campo opcional", value: "(opcional)" },
      { key: "forms.sending", label: "Botón mientras se envía", value: "Enviando…" },
      { key: "visit.service", label: "Visita · campo del servicio", value: "Servicio al que asistirás" },
      { key: "visit.mobile", label: "Visita · campo del celular", value: "Celular" },
      { key: "visit.origin", label: "Visita · grupo de procedencia", value: "¿Desde dónde nos visitas?" },
      { key: "visit.originHint", label: "Visita · ayuda de procedencia", value: "Es opcional: nos ayuda a conectarte con la célula más cercana.", area: true },
      { key: "visit.thanks", label: "Visita · mensaje al enviar", value: "¡Gracias! Recibimos tus datos y te esperamos con los brazos abiertos.", area: true },
      { key: "baptism.date", label: "Bautismo · campo de la fecha", value: "Fecha del bautismo" },
      { key: "baptism.story", label: "Bautismo · campo de la decisión", value: "Cuéntanos tu decisión" },
      { key: "baptism.thanks", label: "Bautismo · mensaje al enviar", value: "¡Gloria a Dios! Recibimos tu inscripción y pronto te contactaremos.", area: true },
      { key: "prayer.topicLabel", label: "Oración · pregunta del motivo", value: "¿Por qué motivo oramos?" },
      { key: "prayer.phone", label: "Oración · campo teléfono", value: "Teléfono" },
      { key: "prayer.email", label: "Oración · campo correo", value: "Correo" },
      { key: "prayer.request", label: "Oración · campo de la petición", value: "Tu petición" },
      { key: "prayer.requestPlaceholder", label: "Oración · petición (texto de ayuda)", value: "Cuéntanos por quién o por qué situación quieres que oremos.", area: true },
      { key: "prayer.submit", label: "Oración · botón", value: "Enviar mi petición" },
      { key: "prayer.thanksHello", label: "Oración · saludo al enviar", value: "Gracias, {nombre}.", hint: "{nombre} se reemplaza por el primer nombre de la persona." },
      { key: "prayer.again", label: "Oración · botón para enviar otra", value: "Enviar otra petición" },
    ],
  },
  {
    id: "acceso",
    title: "Acceso al sistema",
    note: "La pantalla /acceso donde ingresan los servidores. El aviso emergente se edita en Indicaciones de la semana.",
    entries: [
      { key: "acceso.brand", label: "Nombre grande", value: "Zoe" },
      { key: "acceso.kicker", label: "Etiqueta", value: "Control de grupos CEREAL" },
      { key: "acceso.title", label: "Título", value: "Acceso al sistema" },
      { key: "acceso.text", label: "Texto", value: "Ingresa para enviar el informe semanal de tu grupo celular.", area: true },
      { key: "acceso.user", label: "Campo usuario", value: "Usuario" },
      { key: "acceso.password", label: "Campo clave", value: "Clave" },
      { key: "acceso.button", label: "Botón", value: "Ingresar" },
      { key: "acceso.back", label: "Enlace para volver", value: "Volver al inicio" },
      {
        key: "acceso.lines",
        label: "Frases de la ilustración",
        value: "Juan 1:1 | En el principio era el Verbo\nCEREAL | Informe de tu grupo\nSalmo 119:105 | Lámpara es a mis pies tu palabra",
        area: true,
        hint: "Una frase por línea: etiqueta | frase. Se escriben solas en la pantalla de la computadora.",
      },
    ],
  },
  {
    id: "panel",
    title: "Ingreso de administración",
    note: "La pantalla de admi-iglesiazoe donde ingresan los administradores y el superadministrador.",
    entries: [
      { key: "panel.kicker", label: "Etiqueta", value: "Iglesia Cristiana Zoe" },
      { key: "panel.title", label: "Título", value: "Panel de administración" },
      { key: "panel.text", label: "Texto", value: "Gestiona la página web, los informes de las células, los temas, las finanzas y el equipo desde un solo lugar.", area: true },
      { key: "panel.points", label: "Puntos destacados", value: "Página web, textos, imágenes y videos\nInformes y ofrendas de cada célula\nTemas de célula para cada semana\nEquipo, accesos y finanzas", area: true, hint: "Un punto por línea." },
      { key: "panel.choose", label: "Selector · pregunta", value: "¿Cómo ingresas?" },
      { key: "panel.admin", label: "Opción · Administrador", value: "Administrador" },
      { key: "panel.adminNote", label: "Opción · nota de Administrador", value: "Visuales, temas, atmósfera y más" },
      { key: "panel.super", label: "Opción · Superadministrador", value: "Superadministrador" },
      { key: "panel.superNote", label: "Opción · nota de Superadministrador", value: "Acceso total y equipo" },
      { key: "panel.user", label: "Campo usuario", value: "Usuario" },
      { key: "panel.password", label: "Campo clave", value: "Clave" },
      { key: "panel.button", label: "Botón", value: "Ingresar al panel" },
      { key: "panel.serverLink", label: "Enlace para servidores", value: "¿Eres servidor de célula o de red? Ingresa desde la web de la iglesia" },
    ],
  },
] as const satisfies readonly Group[];

export type CopyKey = (typeof copyGroups)[number]["entries"][number]["key"];

const defaults = Object.fromEntries(copyGroups.flatMap((group) => group.entries.map((entry) => [entry.key, entry.value]))) as Record<CopyKey, string>;

export function copyDefault(key: CopyKey) {
  return defaults[key];
}

export function readCopy(settings: Pick<SiteSettings, "copy"> | undefined, key: CopyKey) {
  const value = settings?.copy?.[key];
  return typeof value === "string" && value.trim() ? value : defaults[key];
}

export function readPairs(settings: Pick<SiteSettings, "copy"> | undefined, key: CopyKey) {
  return readCopy(settings, key)
    .split(/\r?\n/)
    .map((line) => {
      const [text, ref = ""] = line.split("|");
      return { text: text.trim(), ref: ref.trim() };
    })
    .filter((pair) => pair.text);
}

export function splitEmphasis(text: string) {
  return text.split(/\*([^*]+)\*/).map((part, index) => ({ text: part, em: index % 2 === 1 })).filter((part) => part.text);
}

export function useCopy() {
  const { settings } = usePage().props as unknown as { settings?: SiteSettings };
  return (key: CopyKey) => readCopy(settings, key);
}
