export type SiteSettings = {
  heroTitle: string;
  heroSubtitle: string;
  city: string;
  address: string;
  sunday: string;
  wednesday: string;
  pastorsLabel: string;
  aboutQuote: string;
  aboutText: string;
  vision: string;
  history: string;
  values: { title: string; text: string }[];
  facebook: string;
  youtube: string;
  instagram: string;
  tiktok: string;
  messengerUrl: string;
  liveUrl: string;
  mapUrl: string;
  liveYoutubeId: string;
  serviceDayMain: string;
  serviceDayWeek: string;
  prayerTopics: string[];
  copy: Record<string, string>;
  bankSoles: string;
  bankSolesCci: string;
  bankDollars: string;
  bankDollarsCci: string;
  bankHolder: string;
  yape: string;
  yapeHolder: string;
  yapeQr: string;
  cardUrl: string;
  phone: string;
  whatsapp: string;
  email: string;
  headingColor: string;
  bodyColor: string;
  accentColor: string;
  paperColor: string;
  stoneColor: string;
  clayColor: string;
  fontPair: "mixed" | "grotesque" | "editorial";
  visitCta: string;
  baptismCta: string;
  essenceTitle: string;
  essenceText: string;
  cellsTitle: string;
  cellsText: string;
  cellsCta: string;
  generationsTitle: string;
  resourcesTitle: string;
  resourcesText: string;
  visitInviteTitle: string;
  visitInviteText: string;
  footerTagline: string;
  aboutKicker: string;
  aboutTitle: string;
  aboutValuesTitle: string;
  aboutValuesText: string;
  ministriesTitle: string;
  ministriesText: string;
  baptismTitle: string;
  baptismLead: string;
  baptismBody: string;
  baptismDateLabel: string;
  baptismRequirementLabel: string;
  baptismRequirement: string;
  baptismDateFallback: string;
  visitTitle: string;
  visitText: string;
  contactTitle: string;
  prayerTitle: string;
  giveTitle: string;
  giveLead: string;
  giveBody: string;
  giveYapeText: string;
  giveCardText: string;
  sermonsTitle: string;
  sermonsEmpty: string;
};

export type SermonSummary = {
  id: string;
  title: string;
  preacher: string | null;
  series: string | null;
  sermon_date: string | null;
  youtube_id: string | null;
  is_live: boolean;
};

export type Ministry = {
  id?: string;
  slug: string;
  name: string;
  age_range: string;
  summary: string;
  body: string;
  sort_order: number;
  accent: string;
  active?: boolean;
};

export type Cell = {
  id: string;
  network_id: string;
  parent_id: string | null;
  number: number;
  code: string;
  leader_name: string | null;
  assistant_name: string | null;
  host_name: string | null;
  address: string | null;
  meeting_day: string | null;
  meeting_time: string | null;
  active: boolean;
};

export type Member = {
  id: string;
  cell_id: string;
  full_name: string;
  phone: string | null;
  active: boolean;
};

export type Theme = {
  id: string;
  title: string;
  audience: string;
  theme_date: string;
  file_type: string | null;
  file_url: string | null;
  download_url: string | null;
};
